fixes #4414 - Payara can close JarFile instances used by current URLClassLoaders
payara/Payara pull request #4441
Opened 2020-01-17 22:02 UTC by bjetal

# Description
Changes the closeCachedJarFiles behavior to only close JarFile instances associated with a "file:" URL.  All others are removed from the cache so they can be closed when no longer in use.  The assumption is that others might be owned by a URLClassLoader, but "file:" is most likely owned by the process requesting the close.  This should allow redeployment of the vast majority of applications on Windows without having to worry about file locks, while letting applications which need unusual Jar file URLs to work.

fixes: https://github.com/payara/Payara/issues/4414

# Testing

### New tests
None provided

### Testing Performed
Tested that it fixes the issue using the application which showed it.

### Test suites executed
None

### Testing Environment
OS: RedHat Linux 7
JDK: OpenJDK 8.0.201
Maven: 3.6.2

# Documentation
N/A

# Notes for Reviewers
N/A

2020-04-03 07:55 UTC, rdebusscher commented
@bjetal We are awaiting the signed CLA (https://github.com/payara/Payara/blob/master/PayaraCLA.pdf) otherwise we need to close this PR.

2020-04-03 20:34 UTC, bjetal commented
I apologize, I thought I had emailed it, but in looking at it I realized I had sent it to the wrong email address.  I have emailed it again, this time to the correct address.

2020-11-24 12:35 UTC, AlanRoth commented
jenkins test please

2020-12-07 18:10 UTC, lprimak requested changes
please update copyright year, otherwise looks good to me

2020-12-07 18:15 UTC, lprimak commented
jenkins test

2020-12-07 18:16 UTC, lprimak commented
@bjetal please merge payara master into your PR and re-push it, your master is out-of-date and doesn't pass security checks anymore,
thanks1

2020-12-29 17:22 UTC, lprimak commented
Marking this as abandoned, but think it needs to be revived as internal, as it is useful

2021-01-06 18:42 UTC, bjetal commented
Sorry to be so slow getting back to this.  It has been updated to the latest master and should be ready to merge.

2021-01-06 19:05 UTC, lprimak approved these changes

2021-01-06 19:05 UTC, lprimak commented
jenkins test

2021-01-06 19:34 UTC, bjetal commented
@lprimak What do you mean by "jenkins test"?  If all you are looking for a unit test, I can probably do that, although it may be a few days until I can get to it.  If you are looking for a test that this "fixes" the overall bug, then I doubt if I will be able to find time to do that.

2021-01-06 20:49 UTC, lprimak commented
That just kicks off Payara internal test suite

2021-01-24 06:11 UTC, merged