FISH-37 URL in DataSourceDefinition overrides serverName
payara/Payara pull request #4870
Opened 2020-09-03 09:28 UTC by Cousjava

## Description
This is a bug fix.

If URL has been set it should override the serverName, causing that to be set to null
to prevent that being using when the DataSource is initialised

Fixes #4385

## Important Info

## Testing
### New tests
New test added in PR, DataSource Definition Tests

### Testing Performed
* Written test
* Debugging Payara and checking the value of serverName is set to null and unused
* Docker test in original issue

### Testing Environment
Zulu JDK 1.8_262 on Ubuntu 20.04 with Maven 3.6.3

2020-09-04 09:28 UTC, Pandrex247 requested changes

2020-09-04 09:28 UTC, Pandrex247 commented on appserver/jdbc/jdbc-runtime/src/main/java/org/glassfish/jdbcruntime/deployment/annotation/handlers/DataSourceDefinitionHandler.java
> +                desc.setServerName(null); //To prevent serverName overriding the URL, always use the URL if the standard properties are not set
Can you make a small change to the `DataSourceDefinitionDescriptor.setServerName(String serverName)` method please to reflect this.

That method sets a boolean of `serverNameSet` to true, which when you're setting it to null probably shouldn't be the case :)

2020-09-04 11:36 UTC, Pandrex247 approved these changes

2020-09-05 06:06 UTC, jGauravGupta commented
jenkins test please

2020-09-05 09:55 UTC, merged