QACI-451 Compile jaxws-tracing on jdk11
payara/Payara pull request #4889
Opened 2020-09-17 10:49 UTC by dmatej

## Description

The module depended on JDK support for JAX-WS. There were also other issues:

- missing separation between test and war packages
- Unstable wasn't inside the war package which caused errors on JDK8 on server side (JDK11 has fix for this)
- the test still fails now, but the result is same on JDK8 and JDK11

## Testing

### Testing Performed
With both JDK11 and JDK8:
```
rm -rf ./target; mvn clean install -pl :payara-samples,:jaxws-tracing -Ppayara-samples,payara-server-managed,unstable -fae
```
With JDK8 only:
```
rm -rf ./target; mvn clean install -pl :payara-samples -Ppayara-samples,payara-server-managed -fae -amd
rm -rf ./target; mvn clean install -pl :payara-samples,:jaxws-tracing -Ppayara-samples,payara-server-managed,unstable -fae -amd
asadmin start-domain; mvn clean install -pl :payara-samples,:jaxws-tracing -Ppayara-samples,payara-server-remote,unstable -fae

```
### Testing Environment
```

mvn -version
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)
Maven home: /home/dmatej/work/apache-maven-3.6.2
Java version: 1.8.0_265, vendor: AdoptOpenJDK, runtime: /usr/lib/jvm/jdk8u265-b01/jre
Default locale: cs_CZ, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-47-generic", arch: "amd64", family: "unix"
```

2020-09-17 10:49 UTC, dmatej commented
Jenkins test please

2020-09-17 10:50 UTC, dmatej commented on appserver/tests/payara-samples/samples/jaxws-tracing/pom.xml
> -
Fixes the issue with dependencies on JDK11

2020-09-17 10:53 UTC, dmatej commented on appserver/tests/payara-samples/test-utils/src/main/java/fish/payara/samples/PayaraTestShrinkWrap.java
> +                .addClasses(Unstable.class)
Missing Unstable caused errors on JDK8, which were different than failures on JDK11

2020-09-17 13:32 UTC, Cousjava requested changes
Copyright years need updating

2020-09-17 13:34 UTC, cubastanley approved these changes
Besides copyright updates LGTM

2020-09-17 14:49 UTC, MarkWareham commented
Made a PR to @dmatej  branch updating copyright. Merge that PR for it to reflect here

2020-09-17 14:50 UTC, MarkWareham commented
jenkins test jdk11 please

2020-09-18 10:54 UTC, MarkWareham approved these changes

2020-09-18 10:59 UTC, Cousjava approved these changes

2020-09-18 11:31 UTC, MarkWareham commented
jenkins test please

2020-09-21 08:53 UTC, merged