Added TLS 1 to 1.3 support test
payara/Payara pull request #4898
Opened 2020-09-22 13:23 UTC by AlanRoth

## Description
A simple test to confirm TLS support by checking available protocols for newly created sockets, for TLS versions 1 to 1.3.

## Important Info
### Blockers
This test fails, as TLSv1.3 is not listed as a  'supported' protocol for sockets, this has been confirmed as a geniune failure.
Couldn't test on JDK11 due to QACI-451.

## Testing

### Testing Performed
Samples remote and managed, JDK8 and JDK11

### Testing Environment
JDK zulu 1.8.0_265 Remote & Managed
JDK zulu 1.8.0_262 Remote & Managed
JDK zulu 1.8.0_152 (Skipped test, as expected)

## Notes for Reviewers
The test will be skipped if TLSv1.3 is not supported for the JDK version it is being run on.

I timeboxed this test to push it out with this test case, but I was writing another test case which can be seen in AlanRoth/QACI-377-extra branch, however encountered a problem with establishing a handshake with the server closing too soon.

2020-09-22 14:59 UTC, Cousjava approved these changes

2020-09-22 16:30 UTC, MarkWareham requested changes
This is the wrong place to put this test. It's not testing the management of the server via REST

2020-09-22 17:12 UTC, AlanRoth commented
> This is the wrong place to put this test. It's not testing the management of the server via REST

Any suggestions to where to move it?

2020-09-24 08:14 UTC, MattGill98 commented
Perhaps a test in nucleus/grizzly/config? The only other place that it's used is nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/HttpConnectorAddress.java, which may also be unit testable. I don't know the intricacies of the TLS integration, so I'll trust your expertise if you think it still needs an integration test - and if so it probably needs a new module in samples (I'm thinking an http module).

2020-09-24 08:39 UTC, AlanRoth commented
> 
> 
> Perhaps a test in nucleus/grizzly/config? The only other place that it's used is nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/HttpConnectorAddress.java, which may also be unit testable. I don't know the intricacies of the TLS integration, so I'll trust your expertise if you think it still needs an integration test - and if so it probably needs a new module in samples (I'm thinking an http module).

I originally stuck it as a unit test inside nucleus, but if we want to extend the tests in the future I think samples is a more fitting place, I had another test case which needed to generate and add self signed certs to the server and samples has handy util for that, but I kicked this out the door as that was an extra and I wanted to timebox it

2020-09-24 10:07 UTC, AlanRoth commented
jenkins test please

2020-09-28 10:37 UTC, MarkWareham approved these changes

2020-09-28 10:37 UTC, MarkWareham commented
QACI-451 mentioned above is now complete

2020-09-28 15:31 UTC, AlanRoth commented
jenkins test please

2020-09-28 16:21 UTC, AlanRoth commented
Failed as expected, waiting for FISH-462

2020-12-23 09:44 UTC, MarkWareham commented
what is current status of this please @AlanRoth ?

2021-01-11 12:31 UTC, AlanRoth commented
Still waiting for anybody to pick up FISH-462, as otherwise, it means introducing a (correctly) failing test. @MarkWareham

2021-01-22 02:29 UTC, lprimak commented
jenkins test

2021-01-22 04:50 UTC, lprimak commented
jenkins test

2021-01-22 04:52 UTC, lprimak commented
jenkins test

2021-01-22 05:00 UTC, lprimak commented
jenkins test

2021-01-22 06:03 UTC, merged