#4657 GlassFishProperties throws NPE if the Properties is null
payara/Payara pull request #4917
Opened 2020-09-27 17:48 UTC by bhanuunrivalled

GlassFishProperties throws NPE if the Properties is null

## Description
Doing a null Check and updated the JAVA DOC

## Important Info
### Blockers

## Testing
### New tests

### Testing Performed

### Testing Environment

## Documentation

## Notes for Reviewers

2020-10-02 06:37 UTC, rdebusscher commented
Hi @bhanuunrivalled ,

Thank you for the PR but before we can accept this, you need to sign the CLA and send it to us.

https://github.com/payara/Payara/blob/master/PayaraCLA.pdf

Thanks
Best Regards
Rudy

2020-10-02 20:23 UTC, bhanuunrivalled commented
Thanks @rdebusscher 

attaching the CLA. 

[PayaraCLA-1.pdf](https://github.com/payara/Payara/files/5320103/PayaraCLA-1.pdf)

2020-10-02 20:29 UTC, bhanuunrivalled commented
hi @rdebusscher ,

can I work on this ?

https://github.com/payara/Payara/issues/4795

please let me know your opinion . I have good knowledge about JSF.

Thanks.

2020-10-03 15:39 UTC, rdebusscher commented
Deleted the previous comment as it contained personal information. The CLA is sent to the correct email address.

2020-11-24 12:36 UTC, AlanRoth commented
jenkins test please

2020-11-24 16:28 UTC, lprimak requested changes

2020-11-24 16:28 UTC, lprimak commented on nucleus/common/simple-glassfish-api/src/main/java/org/glassfish/embeddable/GlassFishProperties.java
> +     * @throws IllegalArgumentException if props is null
`@throws NullPointerException`

2020-11-24 16:28 UTC, lprimak commented on nucleus/common/simple-glassfish-api/src/main/java/org/glassfish/embeddable/GlassFishProperties.java
> +        if(props == null){
this should be `Objects.requireNonNull(props, "props should not be null")`

2020-11-24 16:28 UTC, lprimak commented on nucleus/common/simple-glassfish-api/src/main/java/org/glassfish/embeddable/GlassFishProperties.java
> +        if(props == null){
or something similar to that, introducing a different exception type might break some functionality and introduces unnecessary risks

2021-01-24 18:50 UTC, lprimak commented
Superceded / incorporated into https://github.com/payara/Payara/pull/5101

2021-01-24 18:53 UTC, lprimak commented
@bhanuunrivalled I could not push my changes on top of your PR so I created my own

If you can give me permissions I can reopen this and finish it here

2021-01-24 18:55 UTC, bhanuunrivalled commented
> @bhanuunrivalled I could not push my changes on top of your PR so I created my own
> 
> If you can give me permissions I can reopen this and finish it here

OK @lprimak I give permission

2021-01-24 18:58 UTC, closed without merging

2021-01-24 19:08 UTC, lprimak commented
Sorry, still getting permissino denied
```
remote: Resolving deltas: 100% (16/16), completed with 10 local objects.
To github.com:bhanuunrivalled/Payara.git
 ! [remote rejected]       bhan-fix-3 -> master (permission denied)
error: failed to push some refs to 'git@github.com:bhanuunrivalled/Payara.git'

```

2021-01-24 19:09 UTC, lprimak commented
Was able to push 10 minutes ago but not anymore