FISH-334 Integrate MicroProfile Metrics into Payara Health
payara/Payara pull request #4918
Opened 2020-09-27 21:03 UTC by MeroRai

## Description
Integrated MicroProfile Metrics into Payara Health service. This provides a way to monitor and log the values of metrics exposed by MicroProfile Metrics.

## Testing

### Testing Performed
Manually tested by monitoring metrics for different scopes, using MicroProfile Metrics sample application available in payara samples.

## Documentation
TODO

## Notes for Reviewers

2020-09-28 16:26 UTC, MattGill98 requested changes
Broadly good, well done! Just a few comments which shouldn't require too much invasive change.

The get-command doesn't return the metric checker name in the admin console (so the text field is always empty. Check the field name from the additional properties map.

The syntax of the specified metric is weird, I'd expect underscore notation as the metric appears. Also, why am I limited to specifying only app metrics or only base metrics etc (I suspect it's because of the dot notation as above)? Does the admin console provide any sort of standard way for specifying lists? I really personally hate this string list strategy.

Finally, the processing is a little unoptimised from what I can tell. Where the process is currently:

1. Get measured metric names
2. Get all metrics
3. Filter all metrics by name
4. Concatenate result with the value of each remaining metric

I think it should be:
1. Get names of measured metrics
2. Get those individual metric values (or at least break early to prevent processing each metric in the stream)
3. Concatenate the values

In other words, most of this logic can be removed from the main processing loop

2020-09-28 16:26 UTC, MattGill98 commented on appserver/payara-appserver-modules/healthcheck-metrics/src/main/java/fish/payara/healthcheck/microprofile/metrics/MicroProfileMetricsCheck.java
> +        List<String> metricNames = new ArrayList<>(Arrays.asList(options.getMetricName().split(",")));
I'd remove extra whitespace here

2020-09-28 16:26 UTC, MattGill98 commented on appserver/payara-appserver-modules/healthcheck-metrics/src/main/java/fish/payara/healthcheck/microprofile/metrics/MicroProfileMetricsCheck.java
> +        metricNames.removeAll(Arrays.asList("", null));
This is slow, I'd remove it from the string when removing whitespace to save 2 passes

2020-09-28 16:26 UTC, MattGill98 commented on appserver/payara-appserver-modules/healthcheck-metrics/src/main/java/fish/payara/healthcheck/microprofile/metrics/MicroProfileMetricsCheck.java
> +        MetricsService metricsService = Globals.getDefaultBaseServiceLocator().getService(MetricsService.class);
Is there any reason you're injecting the metrics service fresh each time?

2020-09-28 16:26 UTC, MattGill98 commented on appserver/payara-appserver-modules/healthcheck-metrics/src/main/java/fish/payara/healthcheck/microprofile/metrics/MicroProfileMetricsCheck.java
> +        Map<MetricID, Metric> metricInfos = state.getMetrics().entrySet().stream()
Does this need repeating each loop? Also, users won't be familiar with the dot notation of the metrics - they're mote likely to use underscore notation as it appears in the metrics result

2020-09-28 16:26 UTC, MattGill98 commented on appserver/payara-appserver-modules/healthcheck-metrics/src/main/java/fish/payara/healthcheck/microprofile/metrics/MicroProfileMetricsCheck.java
> +                metrics.isEmpty() ? "The metric you entered doesn't exist under " + registryName : metrics.stream().map(Object::toString).collect(Collectors.joining())));
Can we have a few more variables? I don't find the streaming particularly intuitive here, and the result contains excess whitespace

2020-09-28 16:26 UTC, MattGill98 commented on nucleus/payara-modules/healthcheck-core/src/main/java/fish/payara/nucleus/healthcheck/configuration/MicroProfileMetricsChecker.java
> +    @Attribute
This should be an actual list IMO (`@Element("metric")`), to prevent comma separated strings in XML files - which can cause all sorts of issues!

2020-10-02 13:04 UTC, MattGill98 requested changes
Not happy with the format for specifying metrics, so I've made a PR to Susan's branch which he's agreed to incorporate into this

2020-10-02 15:46 UTC, MeroRai commented
jenkins test please

2020-10-03 16:37 UTC, Pandrex247 commented
Jenkins test please

2020-10-03 18:50 UTC, MeroRai commented
Jenkins test please

2020-10-04 10:51 UTC, MattGill98 approved these changes

2020-10-04 11:53 UTC, MeroRai commented
Jenkins test please

2020-10-04 14:14 UTC, merged