QACI-376 Add test for HTTP Vs Zulu 8.46
payara/Payara pull request #4932
Opened 2020-10-02 08:32 UTC by AlanRoth

## Description
Simple test that deploys a servlet and does a POST request to google.com, expecting a status code that isn't 500.
## Important Info
### Blockers
This test fails on JDK8 5.2020.3+ with a status code 500, passes on 5.2020.2 JDK8 with a 405.

The test passes on JDK11 5.2020.3+ with a 200.

## Testing
### New tests
New HttpSupportTest

### Testing Performed
Payara Samples

### Testing Environment
Tested on Zulu 8_252 and Zulu 11.0.1, 5.2020.2, 5.2020.3, 5.2020.5-SNAPSHOT

## Notes for Reviewers
[qaci-376.zip](https://github.com/payara/Payara/files/5316588/qaci-376.zip)
To use Rudy's reproduer
- unzip qaci-376.zip
- mvn clean package
- cp target/qaci-376.war src/main/docker
- docker build -t qaci-376 src/main/docker
- docker run -d --name qaci-376 -p 8080:8080 qaci-376
- wait a few seconds until server is up
- curl http://localhost:8080/qaci-376/hello → status 500
- docker rm -f qaci-376

2020-10-02 08:51 UTC, AlanRoth commented
jenkins test please

2020-10-02 09:18 UTC, MarkWareham approved these changes

2020-11-20 10:04 UTC, MarkWareham commented
jenkins test please

2020-11-20 10:15 UTC, rdebusscher approved these changes

2020-12-10 09:52 UTC, MattGill98 commented
jenkins test please

2020-12-10 15:57 UTC, lprimak approved these changes

2021-01-11 12:33 UTC, AlanRoth commented
Still waiting for anybody to pick up FISH-515 to make this test case pass

2021-01-20 20:10 UTC, lprimak requested changes
Changes in line with other test (please wait for that)

2021-01-20 20:10 UTC, lprimak commented on appserver/tests/payara-samples/pom.xml
> +                <version>${payara.version}</version>
project.version instead of payara.version

2021-01-22 08:06 UTC, lprimak commented
jenkins test

2021-01-22 08:06 UTC, lprimak approved these changes

2021-01-22 11:30 UTC, merged