FISH-341 Create GCP Secrets Cloud Config Source
payara/Payara pull request #4944
Opened 2020-10-12 09:02 UTC by MattGill98

## Description

This is a new feature, which looks to allow GCP secrets manager to be used as a config source for Payara.

## Documentation

Docs still to be written.

## Notes for Reviewers

Note that although this doesn't perfectly follow the design for an extension, the design is such that moving this provider to an extension would be quite simple. As such a new service is implemented that registers and dynamically updates the config sources. A proxy class is injected to ensure that disabling a config source disables it without requiring a restart

2020-10-12 09:27 UTC, MattGill98 commented
jenkins test please

2020-10-12 11:49 UTC, MattGill98 commented
jenkins test please

2020-10-12 11:50 UTC, MattGill98 commented
jenkins test please

2020-10-12 17:58 UTC, MattGill98 commented
jenkins test please

2020-10-13 07:05 UTC, MattGill98 reviewed
Needs updating to Snapshot

2020-10-13 07:05 UTC, MattGill98 commented on appserver/payara-appserver-modules/microprofile/config-extensions/pom.xml
> +        <version>5.2020.5-SNAPSHOT</version>
```suggestion
        <version>5.2020.6-SNAPSHOT</version>
```

2020-10-13 07:05 UTC, MattGill98 commented
jenkins test please

2020-10-13 09:31 UTC, MeroRai requested changes
Looks good. I left suggestions which you can take into consideration. I noticed some of the comments and code still refer to the Notifier service this will need updating. Finally, some of the class doesn't have a copyright header.

2020-10-13 09:31 UTC, MeroRai commented on appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/gcp/GetGCPSecretsConfigSourceConfiguration.java
> +@Service(name = "get-gcp-secrets-config-source-configuration")
The command is too long in my opinion. I suggest shorting it, for examples: `get-gcp-secrets-configuration`, `get-gcp-config` or `get-gcp-configuration`

2020-10-13 09:31 UTC, MeroRai commented on appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/gcp/SetGCPSecretsConfigSourceConfigurationCommand.java
> +@Service(name = "set-gcp-secrets-config-source-configuration")
Same as my above comment. I suggest shorting the command name

2020-10-13 10:08 UTC, MattGill98 commented
jenkins test please

2020-10-13 10:12 UTC, MattGill98 commented
jenkins test please

2020-10-14 14:10 UTC, MeroRai approved these changes

2020-10-14 14:58 UTC, MattGill98 commented
jenkins test please

2020-10-14 21:37 UTC, merged