QACI-701 Increment version numbers
payara/Payara pull request #4976
Opened 2020-11-03 09:47 UTC by MarkWareham

2020-11-03 09:51 UTC, cubastanley approved these changes

2020-11-03 09:51 UTC, cubastanley commented
Jenkins test please

2020-11-03 10:27 UTC, Pandrex247 requested changes
**Also** missing update to micro `glassfish-version.properties`

2020-11-03 10:27 UTC, Pandrex247 commented on appserver/packager/appserver-base/src/main/docs/README.txt
> +Make sure to also check the Payara Server 5.2020.7 Release Notes as they contain important information: https://docs.payara.fish/docs/5.2020.7/release-notes/release-notes-2020.2.html
```suggestion
Make sure to also check the Payara Server 5.2020.7 Release Notes as they contain important information: https://docs.payara.fish/docs/5.2020.7/release-notes/release-notes-2020-7.html
```
URL is wrong

2020-11-03 14:37 UTC, Pandrex247 requested changes
I can't edit `glassfish-version.properties` from here since you haven't made a change near it. Don't forget it please, it's wrong.

2020-11-03 14:37 UTC, Pandrex247 commented on appserver/packager/appserver-base/src/main/docs/README.txt
> +Payara Server 5.2020.7 Release Notes: https://docs.payara.fish/docs/5.2020.7/release-notes/release-notes-2020.2.html
```suggestion
Payara Server 5.2020.7 Release Notes: https://docs.payara.fish/docs/5.2020.7/release-notes/release-notes-2020-7.html
```

2020-11-03 14:45 UTC, Pandrex247 approved these changes

2020-11-03 14:45 UTC, cubastanley requested changes
Scripts don't account for a snapshot in here and, although I may be overlooking something, I don't see that it needs to be snapshot in this file

2020-11-03 14:45 UTC, cubastanley commented on appserver/extras/payara-micro/payara-micro-boot/src/main/resources/MICRO-INF/domain/branding/glassfish-version.properties
> +update_version=7-SNAPSHOT
```suggestion
update_version=7
```

2020-11-03 14:46 UTC, cubastanley approved these changes

2020-11-05 09:39 UTC, MarkWareham commented
jenkins test please

2020-11-06 09:28 UTC, merged

2020-11-06 09:28 UTC, MarkWareham commented
Overrode Jenkins check as it is a false positive