Use Maven Properties for GF Properties file
payara/Payara pull request #4980
Opened 2020-11-03 17:40 UTC by cubastanley

## Description
Just a small update, makes use of maven properties in the ant build for the glassfish-version.properties file so as to remove some extra margin for error in the release process

## Testing
### Testing Performed
Build and run locally to show correct version number on server startup, additionally looked manually in the file after building and values are correct

2020-11-03 17:57 UTC, Pandrex247 requested changes
Doesn't work.
You get this:

```
java -jar target/payara-micro.jar --version
Payara Micro ${major_version}.${minor_version}.${update_version}. Build Number ${build.number}
```

2020-11-03 18:51 UTC, lprimak commented
Not sure we should be re-inventing the wheel:

https://gist.github.com/lprimak/a66857eb3526a20ac996b43fdc4008fc

2020-12-10 17:44 UTC, lprimak approved these changes

2020-12-23 14:00 UTC, cubastanley commented
Closing as not scheduled for working on at present

2020-12-23 14:00 UTC, closed without merging