FISH-206 @RolesAllowed annotation in method prevents unauthenticated calls to other methods in remote EJB
payara/Payara pull request #4981
Opened 2020-11-04 14:03 UTC by Pandrex247

## Description
Without authorisation being passed, an EJB client would fail to perform a lookup on an EJB if it had a @RolesAllowed annotation if no IOR descriptor and no authentication were provided - it would default to requiring authentication to perform a lookup if any checked method permissions were detected. If the EJB had methods annotated with PermitAll however, this would prevent you from accessing these methods without providing authentication since you could not perform the initial context lookup.

## Important Info
This should ideally be run through the JakartaEE TCK before being merged, due to the security implication of me cracking the door open slightly. 

### Dependant PRs
None

### Blockers
None

## Testing
Added some new tests and ran some small bits of the Jakarta TCK and Java EE7 Samples.

### New tests
Added a new sample to payara-samples, which only runs if using the `payara-server-remote` profile.

It runs the following checks:
* EJB can be injected into a servlet without authentication (working as it did before these changes).
  * Method annotated with `PermitAll` can be accessed (working as it did before these changes).
  * Method annotated with `RolesAllowed` can **not** be accessed (working as it did before these changes).
* Standalone Java client can perform lookup on EJB annotated with a mix of `RolesAllowed` and `PermitAll` annotations
  * Method annotated with `PermitAll` can be accessed
  * Method annotated with `RolesAllowed` can **not** be accessed
* Standalone Java client can **not** perform lookup on an EJB annotated _only_ with `RolesAllowed`.

## Documentation
N/A

## Notes for Reviewers
I can't find the CSIv2 spec so I don't know if this default behaviour of locking the door for lookups if a single checked method is detected is expected.

2020-11-05 12:29 UTC, Pandrex247 commented
Jenkins test please

2020-11-11 11:04 UTC, Pandrex247 commented
Jenkins test please

2020-11-11 11:06 UTC, Pandrex247 commented
Ran through Jakarta TCK and appears to not break any security tests.

2020-11-12 10:12 UTC, jbee reviewed
I guess it misses this commint https://github.com/payara/Payara-Enterprise/pull/237/commits/8294ef5bce17de762959e1509cede905d85923d5 ?

2020-11-12 12:01 UTC, Pandrex247 commented
Jenkins test please

2020-11-12 13:04 UTC, dmatej requested changes

2020-11-12 13:04 UTC, dmatej commented on appserver/tests/payara-samples/samples/rolesallowed-unprotected-methods/pom.xml
> +        <version>5.2020.6-SNAPSHOT</version>
Rebase to a new snapshot version, please ... now it is 5.2020.7-SNAPSHOT

2020-11-12 13:04 UTC, dmatej commented on appserver/tests/payara-samples/samples/rolesallowed-unprotected-methods/rolesallowed-unprotected-methods-client/pom.xml
> +        <version>5.2020.6-SNAPSHOT</version>
Rebase to a new snapshot version, please ... now it is 5.2020.7-SNAPSHOT

2020-11-12 13:04 UTC, dmatej commented on appserver/tests/payara-samples/samples/rolesallowed-unprotected-methods/rolesallowed-unprotected-methods-common/pom.xml
> +        <version>5.2020.6-SNAPSHOT</version>
Rebase to a new snapshot version, please ... now it is 5.2020.7-SNAPSHOT

2020-11-12 13:04 UTC, dmatej commented on appserver/tests/payara-samples/samples/rolesallowed-unprotected-methods/rolesallowed-unprotected-methods-server/pom.xml
> +        <version>5.2020.6-SNAPSHOT</version>
Rebase to a new snapshot version, please ... now it is 5.2020.7-SNAPSHOT

2020-11-12 13:06 UTC, dmatej commented
Except those version number it seems ok, it passed all tests on my computer ... should I try also some TCK subset for sure?

2020-11-13 09:27 UTC, Pandrex247 commented
Jenkins test please

2020-11-13 15:24 UTC, merged