FISH-338 Create HashiCrop MicroProfile Config Source
payara/Payara pull request #4982
Opened 2020-11-04 17:58 UTC by MeroRai

## Description
This is a feature, that allows you to fetch secrets from HashiCrop Vault to be used as a config source for Payara.

## Documentation
TODO

2020-11-11 10:35 UTC, jbee reviewed
Don't really know what a hashi crop is so I just can reason about general things.

2020-11-11 10:35 UTC, jbee commented on appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/hashicrop/model/SecretHolder.java
> +public class SecretHolder {
A comment explaining why this wrapper is used would be nice.

2020-11-13 14:30 UTC, MeroRai commented on appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/hashicrop/HashiCropSecretsConfigSource.java
> +        return getProperties().get(propertyName);
@jbee, would you be able to raise a JIRA for this issue as this will need to be changed in multiple other config sources.

2020-11-13 15:42 UTC, jbee commented on appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/hashicrop/HashiCropSecretsConfigSource.java
> +        return getProperties().get(propertyName);
Created FISH-756

2020-11-14 18:25 UTC, MeroRai commented
jenkins test please

2020-11-16 09:20 UTC, MattGill98 commented
jenkins test please

2020-11-16 14:55 UTC, MattGill98 commented
jenkins test please

2020-11-16 15:07 UTC, cubastanley commented
Jenkins test please

2020-11-16 15:14 UTC, MarkWareham commented
jenkins test please

2020-11-16 15:21 UTC, cubastanley commented
Jenkins test please

2020-11-16 15:24 UTC, cubastanley commented
jenkins test please

2020-11-16 15:27 UTC, cubastanley commented
jenkins test please

2020-11-16 15:36 UTC, cubastanley commented
jenkins test please

2020-11-19 12:35 UTC, jbee commented
@MeroRai is this ready to be re-reviewed?

2020-11-20 00:06 UTC, MeroRai commented
jenkins test please

2020-11-20 00:09 UTC, MeroRai commented
@jbee @MattGill98 is reviewing it now. Thank you for your earlier reviews.

2020-11-20 11:04 UTC, MattGill98 requested changes

2020-11-20 11:04 UTC, MattGill98 commented on appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/hashicorp/HashiCorpSecretsConfigSource.java
> +                .target(configuration.getVaultAddress() + "/v1" + configuration.getPath());
This line is confusing as a user. Should the path include the `/data` for a v2 API? Should it include the `/kv`? If this feature only supports KV stores I'd like to see that taken. I'd like this cleared up and explained in the admin console. Also I'd like to see failed responses log the endpoint that is actually called so they can debug it

2020-11-20 17:06 UTC, MeroRai commented
jenkins test please

2020-11-20 19:51 UTC, MeroRai commented
jenkins test please

2020-11-23 15:12 UTC, MeroRai commented
jenkins test please

2020-11-24 09:28 UTC, MattGill98 requested changes
Looking much better, just needs a null check before the HTTP calls

2020-11-24 09:28 UTC, MattGill98 commented on appserver/payara-appserver-modules/microprofile/config-extensions/src/main/java/fish/payara/microprofile/config/extensions/hashicorp/HashiCorpSecretsConfigSource.java
> +
Each method needs a null check to see if the other parameters are null

2020-11-24 09:47 UTC, MattGill98 approved these changes
Discussed with Susan and this scenario is unlikely

2020-11-24 09:47 UTC, merged

2022-08-11 09:30 UTC, marif1989 commented
We have at least 70 Java applications and now trying to use the secrets that is saved from vault. The plan is to create no-root tokens in order to access the secrets from vault.
configured all required settings in payara5 server and able to connect to vault and able to get all the required secrets via non-root token.
The problem is non-root tokens are expiring too soon and payara5 is not renewing non-root token automatically and as soon as the token expire connection breaks and no secrets can be fetched from vault.

Reason to use non-root token is java applications must not see the secrets of each other.

Please suggest the possible ways to achieve requirement

Vault configuration is like:

Non-root token A must access only - /DEV/APP-A
Non-root token B must access only - /DEV/APP-B