Hazelcast 4.2 w/tenant control
payara/Payara pull request #5013
Opened 2020-11-28 06:15 UTC by lprimak

## Description

## Important Info
### Blockers

## Testing
### New tests

### Testing Performed

### Testing Environment

## Documentation

## Notes for Reviewers

2020-11-28 23:05 UTC, lprimak commented
For reference, old PR https://github.com/payara/Payara/pull/4762

2020-12-22 16:12 UTC, MarkWareham approved these changes
LGTM. Some suggestions, observations

2020-12-22 16:12 UTC, MarkWareham commented on nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/PayaraHazelcastTenant.java
> +            } catch (InterruptedException ex) {
are you intentionally swallowing the exception?

2020-12-22 16:12 UTC, MarkWareham commented on nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/PayaraHazelcastTenant.java
> +        return true;
```suggestion
        if (!contextInstance.isLoaded()) {
            return true;
        }
        if (!tenantable.requiresTenantContext() || tenantNotRequired(tenantable)) {
            return true;
        }
        lock.lock();
        try {
            String componentId = contextInstance.getInstanceComponentId();
            int unavailableCount = blockedCounts.compute(componentId, (k, v) -> v == null ? 0 : ++v);
            log.log(unavailableCount > 100 ? Level.INFO : Level.FINEST,
                    String.format("BLOCKED: tenant not available: %s, module %s, Operation: %s",
                            componentId, moduleName, tenantable.getClass().getName()));
            if (unavailableCount > 100) {
                blockedCounts.remove(componentId);
            }
            condition.await(100, TimeUnit.MILLISECONDS);
        } catch (InterruptedException ex) {
        } finally {
            lock.unlock();
        }
        return false;        
```

2021-01-28 19:47 UTC, lprimak commented
Waiting for Hazelcast 4.2 to be released in March

2021-03-25 14:51 UTC, lprimak commented
jenkins test

2021-03-25 18:04 UTC, lprimak commented
jenkins test

2021-03-26 15:38 UTC, dmatej requested changes
Not sure if it is alright to merge it to master, because I am sure it breaks something ... seems Metrics + Payara + Hazelcast have some common issue ... not sure if we can postpone that or if the fix should be part of this PR.
But I have a reproducer ... https://github.com/payara/Payara/pull/5019

```
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT: [2021-03-26T15:01:54.685+0000] [Payara 5.2021.2-SNAPSHOT] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=123 _ThreadName=http-thread-pool::http-listener-2(5)] [timeMillis: 1616770914685] [levelValue: 900] [[
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:   StandardWrapperValve[microprofile-metrics-resource]: Servlet.service() for servlet microprofile-metrics-resource threw exception
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT: java.lang.NullPointerException
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at fish.payara.appserver.context.JavaEEContextUtilImpl.isLoaded(JavaEEContextUtilImpl.java:149)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at fish.payara.appserver.context.JavaEEContextUtilImpl.isInvocationLoaded(JavaEEContextUtilImpl.java:118)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at fish.payara.nucleus.hazelcast.PayaraHazelcastTenantFactory.saveCurrentTenant(PayaraHazelcastTenantFactory.java:64)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at com.hazelcast.spi.impl.tenantcontrol.impl.TenantControlServiceImpl.initializeTenantControl(TenantControlServiceImpl.java:136)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:234)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:219)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.getOrCreateProxyFuture(ProxyRegistry.java:186)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.getOrCreateProxy(ProxyRegistry.java:166)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getDistributedObject(ProxyServiceImpl.java:153)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at com.hazelcast.instance.impl.HazelcastInstanceImpl.getDistributedObject(HazelcastInstanceImpl.java:354)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at com.hazelcast.instance.impl.HazelcastInstanceImpl.getMap(HazelcastInstanceImpl.java:173)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at com.hazelcast.instance.impl.HazelcastInstanceProxy.getMap(HazelcastInstanceProxy.java:95)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at fish.payara.nucleus.store.ClusteredStore.get(ClusteredStore.java:190)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at fish.payara.nucleus.microprofile.config.source.ClusterConfigSource.getValue(ClusterConfigSource.java:83)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at fish.payara.nucleus.microprofile.config.source.ClusterConfigSource.getOrdinal(ClusterConfigSource.java:74)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at fish.payara.nucleus.microprofile.config.spi.ConfigSourceComparator.compare(ConfigSourceComparator.java:54)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at fish.payara.nucleus.microprofile.config.spi.ConfigSourceComparator.compare(ConfigSourceComparator.java:50)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at java.util.TimSort.sort(TimSort.java:220)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at java.util.Arrays.sort(Arrays.java:1438)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at java.util.List.sort(List.java:478)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at java.util.Collections.sort(Collections.java:177)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at fish.payara.nucleus.microprofile.config.spi.PayaraConfig.<init>(PayaraConfig.java:106)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at fish.payara.nucleus.microprofile.config.spi.ConfigProviderResolverImpl.getConfig(ConfigProviderResolverImpl.java:280)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at fish.payara.nucleus.microprofile.config.spi.ConfigProviderResolverImpl.getConfig(ConfigProviderResolverImpl.java:306)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at fish.payara.nucleus.microprofile.config.spi.ConfigProviderResolverImpl.getConfig(ConfigProviderResolverImpl.java:213)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:85)
16:01:54.688  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at fish.payara.microprofile.metrics.rest.MetricsResource.getGlobalTags(MetricsResource.java:175)
16:01:54.689  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at fish.payara.microprofile.metrics.rest.MetricsResource.getOutputWriter(MetricsResource.java:162)
16:01:54.689  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at fish.payara.microprofile.metrics.rest.MetricsResource.processRequest(MetricsResource.java:124)
16:01:54.689  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at fish.payara.microprofile.metrics.rest.MetricsResource.doGet(MetricsResource.java:288)
16:01:54.689  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
16:01:54.689  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
16:01:54.689  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1636)
16:01:54.689  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:259)
16:01:54.689  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
16:01:54.689  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:757)
16:01:54.689  INFO [docker-java-stream-176109586]                  D-PAYARA:64 - STDOUT:        at org.apache.catalina.core.St [...]

2021-03-26 15:38 UTC, merged

2021-03-26 15:38 UTC, dmatej commented
Wow, too late :D

2021-03-26 15:39 UTC, MattGill98 commented
Does this need reverting @dmatej?

2021-03-26 15:48 UTC, dmatej commented
I vote to continue with it if we fix it soon (next week). If not and it would break anything else, we will revert it.

2021-03-26 16:58 UTC, lprimak commented
turned out a very simple fix. Good job @dmatej for discovering it.