QACI-592 Fixed build consistency when using QuickBuild
payara/Payara pull request #5036
Opened 2020-12-07 11:57 UTC by dmatej

## Testing

### Testing Performed
mvn clean install -pl :extras,:docker-images -PQuickBuild,BuildExtras,BuildDockerImages -amd # time: 6:37
mvn clean install -pl :extras,:docker-images -PBuildExtras,BuildDockerImages -amd # time: 7:51

The issue was introduced in commits under CUSTCOM-130

2020-12-07 11:57 UTC, dmatej commented
Jenkins test please

2020-12-07 15:52 UTC, Pandrex247 commented
Not sure this is really "build consistency", seems more like you're just trying to have the BuildDockerImages profile mirror the QuickBuild behaviour.

As a rundown of the profiles:
QuickBuild disables building of the _payara-ml_, _payara-web_, and _payara-web-ml_ distributions of Payara Server - so just _payara_ and _payara-micro_ get built rather than all 5.
BuildExtras activates the _embedded_ (and also currently the certificate management) modules. There used to be more under extras which we skipped as a part of the normal build (e.g. Micro) so the name of this profile is a bit misleading atm.
BuildDockerImages activates building of the docker image modules. This was kept separate from the BuildExtras profile due to the possibility of not having Docker installed.

To build the docker images you don't need BuildExtras. There is no Docker image that depends on embedded (or cert management).

2020-12-07 16:30 UTC, Pandrex247 requested changes
Assuming your intention is to make it so that when QuickBuild is used with BuildDockerImages it skips trying to build the payara-server-web docker image, this doesn't seem to work:

`mvn clean install -PQuickBuild,BuildDockerImages`

```
[ERROR] Failed to execute goal on project docker-images-tests: Could not resolve dependencies for project fish.payara.extras:docker-images-tests:jar:5.2020.8-SNAPSHOT: Could not find artifact fish.payara.extras:server-web-docker-image:pom:5.2020.8-SNAPSHOT
```

2020-12-07 17:24 UTC, dmatej commented
I'm not sure now, but I think there was a reason why I always enabled BuildExtras with BuildDockerImages, maybe it is something fixed now. The second comment is certainly my mistake, thanks for the review!

2020-12-07 17:25 UTC, lprimak approved these changes

2020-12-07 17:27 UTC, dmatej commented
If I would exclude also remaining except payara-web, DockerNodesITest would fail, because it depends on all except web profile.

2020-12-07 19:20 UTC, dmatej commented
AHA! The BuildExtras + extras is here to build also zip files, while it expects that everything else was built with QuickBuild enabled where I can use -TC8 so have it asap. So it is just and example, you can combine modules, profiles, as you need. 
The point is that it should pass if it is not some nonsense.

So the only issue is with that dependency, you are right the there is much more possible examples which must pass.

2020-12-08 07:08 UTC, dmatej commented
Jenkins test please

2020-12-08 11:07 UTC, Pandrex247 approved these changes

2020-12-08 11:37 UTC, merged