[QACI-410] - Classloader Leak Tracking
payara/Payara pull request #5063
Opened 2020-12-18 17:14 UTC by cubastanley

## Description
Technically a new feature - adds a new sample app that allows for tracking the number of instances of WebappClassLoader before and after a series of deployments

## Important Info

## Testing
### New tests
Currently removed classloader leak test in samples - removed due to intergration blockers

### Testing Performed
Manual testing, deployed locally and returns an appropriate value for instance count

### Testing Environment
OSX, Zulu JDK 1.8.0_272

## Documentation
README included with usage instructions

## Notes for Reviewers
This is an internal tool as it were, a step in the direction of being able to test for Classloader instance leaks (i.e. instances of WebappClassLoader that aren't garbage collected when they should be) 

Excuse the formatting in the Samples pom - NetBeans decided it would be fun to insert a new line between every line in the file

2020-12-18 18:48 UTC, lprimak requested changes

2020-12-18 18:48 UTC, lprimak commented on appserver/tests/payara-samples/classloader-data-api/pom.xml
> +    <dependencyManagement>
no need for Jersey, use plain jax-js APIs instead

2020-12-18 18:48 UTC, lprimak commented on appserver/tests/payara-samples/classloader-data-api/pom.xml
> +            <groupId>org.glassfish.jersey.containers</groupId>
same here, use plain jax-rs APIs

2020-12-18 18:48 UTC, lprimak commented on appserver/tests/payara-samples/classloader-data-api/pom.xml
> +    <build>
no need for this section at all, use properties equivalent
This way you don't override the complier plugin version at all

2020-12-18 18:48 UTC, lprimak commented on appserver/tests/payara-samples/classloader-data-api/src/main/java/fish/payara/samples/classloaderdata/InstanceCountService.java
> +/*
full Payara copyright

2020-12-18 18:48 UTC, lprimak commented on appserver/tests/payara-samples/classloader-data-api/src/main/java/fish/payara/samples/classloaderdata/InstanceCountService.java
> +public class InstanceCountService {
Not sure this is necessary at all

2020-12-18 18:48 UTC, lprimak commented on appserver/tests/payara-samples/classloader-data-api/src/main/java/fish/payara/samples/classloaderdata/InstanceCountTracker.java
> +public class InstanceCountTracker {
I would move instance count into own class, not have instance counts in different classes.
Minimize changes to WebappClassLoader

Also, this doesn't touch non-webapp (jar, ear etc) class loaders

2020-12-18 18:48 UTC, lprimak commented on appserver/tests/payara-samples/classloader-data-api/src/main/webapp/WEB-INF/web.xml
> +<?xml version="1.0" encoding="UTF-8"?>
no need for this file, use plain jax-rs APIs

2020-12-18 18:48 UTC, lprimak commented on appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
> +    private static int INSTANCE_COUNT;
possible race condition, should be AtomicInteger

2020-12-18 18:48 UTC, lprimak commented on appserver/tests/payara-samples/classloader-data-api/src/main/java/fish/payara/samples/classloaderdata/InstanceCountTracker.java
> +            ((WebappClassLoaderFinalizer)referenceFromQueue).cleanupAction();
this cast is a code smell, this needs to be refactored

2020-12-18 18:48 UTC, lprimak commented on appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
> + * Copyright (c) 1997-2020 Oracle and/or its affiliates. All rights reserved.
oracle copyrights should not be changed

2020-12-18 18:48 UTC, lprimak commented on appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoaderFinalizer.java
> +// Portions Copyright [2020] [Payara Foundation and/or its affiliates]
needs full copyright, not just portions

2020-12-18 18:50 UTC, lprimak commented on appserver/tests/payara-samples/pom.xml
> +--><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0
I would just revert and start this file over again

2020-12-22 05:27 UTC, lprimak requested changes
It was good, now much, much better. Just minor things left

2020-12-22 05:27 UTC, lprimak commented on appserver/tests/payara-samples/classloader-data-api/pom.xml
> +        <jersey.version>3.0.0</jersey.version>
remove jersey

2020-12-22 05:27 UTC, lprimak commented on appserver/tests/payara-samples/classloader-data-api/pom.xml
> +        WebappClassLoader from an instance of Payara Server</description>
Need the same functionality for ASURLClassLoader (parent of EARClassLoader EJBClassLoader etc)

2020-12-22 05:27 UTC, lprimak commented on appserver/tests/payara-samples/classloader-data-api/src/main/java/fish/payara/samples/classloaderdata/InstanceCountService.java
> +public class InstanceCountService {
I still see no point in this class, it does nothing.
InstanceCountTracker can be used directly.

2020-12-22 05:27 UTC, lprimak commented on appserver/tests/payara-samples/classloader-data-api/src/main/java/fish/payara/samples/classloaderdata/InstanceCountTracker.java
> +    public static int getInstanceCount() {
needs intent javadoc

2020-12-22 05:27 UTC, lprimak commented on appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
> +    public static ReferenceQueue<WebappClassLoader> referenceQueue = new ReferenceQueue<WebappClassLoader>();
should be final

2020-12-22 05:27 UTC, lprimak commented on appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
> +    public static ArrayList<WebappClassLoaderFinalizer> list = new ArrayList<WebappClassLoaderFinalizer>();
should be final

2020-12-22 05:27 UTC, lprimak commented on appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
> +    {
is isn't really standard, you should move it down into the `static` block

2020-12-23 16:06 UTC, sgflt commented on appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
> +        INSTANCE_COUNT.set(INSTANCE_COUNT.get() + 1);
This does not seem to be thread safe too.

2020-12-23 18:03 UTC, lprimak requested changes
There are code duplication smells still in the code, with duplicated parts in ASURLClassLaoder vs. WebappClassLoader. This can be refactored into another lass

2020-12-25 06:39 UTC, lprimak approved these changes

2020-12-25 06:40 UTC, lprimak commented
jenkins test

2020-12-25 19:43 UTC, sgflt commented on nucleus/common/common-util/src/main/java/org/glassfish/common/util/InstanceCounter.java
> +    private static final Map<Class<?>, Count> INSTANCE_COUNT = new ConcurrentHashMap<>();
I would use ConcurrentMap interface to point that there is expected concurrency.

```suggestion
    private static final ConcurrentMap<Class<?>, Count> INSTANCE_COUNT = new ConcurrentHashMap<>();
```

2020-12-26 00:54 UTC, lprimak commented
Jenkins test

2020-12-26 01:16 UTC, lprimak commented
jenkins test

2020-12-26 21:58 UTC, merged