FISH-753 Remove production domain template from Payara Server Community distributions
payara/Payara pull request #5099
Opened 2021-01-22 12:19 UTC by Pandrex247

## Description
Removes the _production_ domain template from the Community distributions.

## Important Info
### Blockers
None

## Testing
### New tests
Nope

### Testing Performed
Built the server and checked that the template is no longer present.

Started Micro with https enabled and an app deployed, poking on HTTPS port worked and no **_new_** expired certs in log (though there are some)

### Testing Environment
Windows 10, JDK 8

## Documentation
Nada

## Notes for Reviewers
Zilch

2021-01-22 12:20 UTC, Pandrex247 commented
Jenkins test please

2021-01-22 17:16 UTC, Cousjava requested changes
Copyright year needs updating

2021-01-22 17:29 UTC, Pandrex247 commented
Jenkins test please

2021-01-28 09:38 UTC, MattGill98 approved these changes

2021-01-28 09:38 UTC, MattGill98 commented
jenkins test please

2021-01-28 10:23 UTC, MeroRai approved these changes

2021-01-28 14:31 UTC, merged

2021-01-28 18:27 UTC, lprimak commented
@MattGill98 @Pandrex247 This is causing failures in nightly build: http://192.168.1.120:8080/job/build/2807/