FISH-1076 hotDeploy runtime option support in Payara Micro
payara/Payara pull request #5143
Opened 2021-03-01 05:14 UTC by jGauravGupta

## Description
This is a feature PR to pass `hotDeploy` runtime option on Payara Micro startup to save deployment state and read `.reload` file to fetch modified files and metadata details.

## Testing

### Testing Performed
Manually Tested with VSCode hotDeploy integration feature

### Testing Environment
VSCode 1.53.2, Windows 10, JDK 8

2021-03-01 15:23 UTC, OndroMih requested changes

2021-03-01 15:23 UTC, OndroMih commented on nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/DynamicReloader.java
> +        boolean hotDeploy = Boolean.TRUE.toString().equals(reloadFile.get(DeployCommandParameters.ParameterNames.HOT_DEPLOY));
Why not use `Boolean.parseBoolean`?
```suggestion
        boolean hotDeploy = Boolean.parseBoolean(reloadFile.get(DeployCommandParameters.ParameterNames.HOT_DEPLOY));
```

2021-03-01 15:23 UTC, OndroMih commented on nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/DynamicReloader.java
> +            boolean metadataChanged = Boolean.TRUE.toString().equals(reloadFile.getProperty(DeployCommandParameters.ParameterNames.METADATA_CHANGED));
```suggestion
            boolean metadataChanged = Boolean.parseBoolean(reloadFile.getProperty(DeployCommandParameters.ParameterNames.METADATA_CHANGED));
```

2021-03-01 15:23 UTC, OndroMih commented on nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/DynamicReloader.java
> +            }
The input stream should be closed. The [Javadoc](https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html#load-java.io.InputStream-) states: "The specified stream remains open after this method returns."
```suggestion
            try (InputStream istream = new FileInputStream(reloadFile) {
                prop.load(istream);
            } catch (Exception ex) {
                // skip
            }
```

2021-03-04 09:31 UTC, MeroRai approved these changes

2021-03-10 02:23 UTC, lprimak commented
@OndroMih Looks like your review was satisfied no?

2021-03-10 02:23 UTC, lprimak commented
jenkins test

2021-03-10 02:31 UTC, lprimak commented
Build failed...

2021-03-10 06:10 UTC, lprimak commented on nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/DynamicReloader.java
> +            try (InputStream istream = new FileInputStream(reloadFile) {
missing paren here

2021-03-11 13:08 UTC, jGauravGupta commented
jenkins test please

2021-03-11 14:02 UTC, jGauravGupta commented
jenkins test please

2021-03-12 09:16 UTC, OndroMih approved these changes

2021-03-12 09:39 UTC, merged