Payara Micro application deployment testcase
payara/Payara pull request #5165
Opened 2021-03-15 09:21 UTC by jGauravGupta

## Description
This is a test case to deploy sample web application to Payara Micro instance locally(similar to David's docker container tests).

2021-03-15 09:28 UTC, jGauravGupta commented
jenkins test please

2021-03-15 10:19 UTC, dmatej requested changes

2021-03-15 10:19 UTC, dmatej commented on appserver/tests/payara-samples/micro-programmatic/src/test/java/fish/payara/samples/programatic/DeployApplicationTest.java
> +        server.stop();
I would move the server variable to a field and the server.stop to a new method:
```
@After
public void stopServer() {
  if (server != null) {
    server.stop();
  }
}
```

2021-03-25 09:32 UTC, jGauravGupta commented
jenkins test please

2021-03-26 12:02 UTC, dmatej approved these changes
Passed on my machine :-)

`mvn clean install -Pfastest,QuickBuild -TC6; mvn clean install -Ppayara-samples,payara-micro-managed`

2021-03-26 15:18 UTC, merged