FISH-786 FISH-1521 FISh-385 Revert of external security connectors integration
payara/Payara pull request #5351
Opened 2021-07-15 21:10 UTC by OndroMih

After replacing the security connectors implementation with integration of external security connectors, there are failures in Jakarta EE TCK.

Reverting the following PRs related or dependent on the integration of external security connectors:

* https://github.com/payara/Payara/pull/5265
* https://github.com/payara/Payara/pull/5338

This also reverts a few other PRs that only increased the version of the connectors dependency as the new versions of connectors were released.

Leaving the update of the MicroProfile dependency from version 4.0 to 4.0.1, because that doesn't break anything and fixes a potential issue with dependencies.

2021-07-15 22:26 UTC, Pandrex247 approved these changes

2021-07-15 22:27 UTC, Pandrex247 commented
Jenkins test please

2021-07-16 08:07 UTC, Pandrex247 commented
`oauth2-client-integration:5.2021.5-SNAPSHOT`
Presumably you need to change some snapshots to finals

2021-07-16 09:06 UTC, cubastanley requested changes
Final versions

2021-07-16 09:06 UTC, cubastanley commented on appserver/payara-appserver-modules/security-oauth2/pom.xml
> +        <version>5.2021.5-SNAPSHOT</version>
```suggestion
        <version>5.2021.5</version>
```

2021-07-16 09:06 UTC, cubastanley commented on appserver/payara-appserver-modules/security-openid/pom.xml
> +        <version>5.2021.5-SNAPSHOT</version>
```suggestion
        <version>5.2021.5</version>
```

2021-07-16 09:06 UTC, cubastanley commented
Jenkins test please

2021-07-20 13:27 UTC, merged

2021-07-20 13:28 UTC, Pandrex247 commented
Force merging since MP TCKs are now attempting to run additional tests which would fail against this branch (through no fault of its own)