FISH-5639 Added warning message to change-master-password command
payara/Payara pull request #5370
Opened 2021-08-04 10:27 UTC by kalinchan

## Description

Added warning message to change-master-password command to warn about additional truststores not being re-encrypted 

## Testing
### Testing Performed

Ran command to see if warning message appeared.
### Testing Environment

openjdk version "1.8.0_292" 
ubuntu 20.04 
maven 3.6.3

2021-08-04 12:41 UTC, kalinchan commented
jenkins test

2021-08-04 13:14 UTC, Pandrex247 requested changes
I think this is too simple - it'll print out the warning even if you haven't got any additional key or trust stores. It should print the warning if they've been configured and not otherwise to prevent confusion.

I'd also change the message to be a bit less technical, but also make it more specific by pointing at the actual stores - something along the lines of:
 `The passwords of additional key stores xyz,asd,ijk and trust stores lkj,gfd,cvb have not been changed - please update these manually to continue using them.`

2021-08-04 13:14 UTC, Pandrex247 commented on nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/ChangeMasterPasswordCommand.java
> +            System.out.println("WARNING: Additional Truststores are not re-encrypted, it is your responsibility to do this.");
I wouldn't use System.out - its use is generally discouraged.

Use `Logger.getLogger(CLICommand.class.getPackage().getName());`

2021-08-13 10:40 UTC, kalinchan commented
jenkins test

2021-08-17 10:11 UTC, Pandrex247 requested changes

2021-08-17 10:11 UTC, Pandrex247 commented on nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/LocalServerCommand.java
> +                }
I don't think you should exit the loop here.

Additional key & trust stores are defined at the config level, which typically goes like this:
1. server-config
2. default-config
3. extra-config1
4. extra-config2
5. ...

If you defined extra stores in both the server-config (for the DAS) and in extra-config1 (for an instance), you would only be warned about needing to change the stores for those defined in server-config.

Also this has a small flaw in that if you only defined additional key stores, your results would get overwritten. For example, if you defined additional key stores in server-config and default-config, only the additional keystores in default-config would be listed.

So I think you should drop this exit clause and iterate over the entire list, and make sure you append to the value if there's one present (see [Map.computeIfPresent](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#computeIfPresent-K-java.util.function.BiFunction-))

2021-08-17 16:28 UTC, Pandrex247 requested changes

2021-08-17 16:28 UTC, Pandrex247 commented on nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/LocalServerCommand.java
> +                        Arrays.toString(additionalTrustandKeyStores.get("additionalKeyStores").split(":")));
Not strictly related to this PR, but I suspect the additional key/trust store functionality doesn't work on Windows for the same reason as this...

2021-08-18 12:22 UTC, kalinchan commented
jenkins test

2021-08-18 13:23 UTC, kalinchan commented
jenkins test

2021-08-18 15:39 UTC, Pandrex247 approved these changes
One super minor change, but otherwise 👍

2021-08-18 15:39 UTC, Pandrex247 commented on nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/LocalServerCommand.java
> +    protected void checkAdditionalTrustandKeyStores() throws IOException, XMLStreamException {
```suggestion
    protected void checkAdditionalTrustAndKeyStores() throws IOException, XMLStreamException {
```

2021-08-18 15:39 UTC, Pandrex247 commented on nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/ChangeNodeMasterPasswordCommand.java
> +            checkAdditionalTrustandKeyStores();
```suggestion
            checkAdditionalTrustAndKeyStores();
```

2021-08-18 15:39 UTC, Pandrex247 commented on nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/ChangeMasterPasswordCommandDAS.java
> +                checkAdditionalTrustandKeyStores();
```suggestion
                checkAdditionalTrustAndKeyStores();
```

2021-08-18 15:42 UTC, kalinchan commented
jenkins test

2021-08-19 08:26 UTC, merged

2021-09-01 08:10 UTC, aubi reviewed
--deleted, mistake--