FISH-5751 Upgrade ASM to version 9.1
payara/Payara pull request #5426
Opened 2021-09-27 16:06 UTC by kalinchan

## Description

Upgrade ASM to version 9.1
## Important Info
### Blockers

N/A
## Testing
### New tests

N/A
### Testing Performed

Built Payara
### Testing Environment

ubuntu 20.04 Maven 3.6.3 openjdk version "1.8.0_292"
## Documentation

N/A
## Notes for Reviewers

N/A

2021-09-27 16:06 UTC, kalinchan commented
jenkins test

2021-09-27 16:34 UTC, Pandrex247 requested changes
You'll need to fiddle with OSGi to get this to play ball

2021-10-01 08:44 UTC, kalinchan commented
jenkins test

2021-10-04 08:40 UTC, Pandrex247 approved these changes

2021-10-04 08:56 UTC, merged