FISH-5703 Option to Improve Logging Speed
payara/Payara pull request #5493
Opened 2021-11-08 16:28 UTC by JamesHillyard

## Description
A new feature allowing users to skip the forced .toString() on all parameters when logging. The command to set this property has been added to set-log-attributes and the admin console. This property is updated dynamically and doesn't need a server restart for the logging changes to take affect.

## Important Info
### Blockers
None

## Testing
### New tests
None

### Testing Performed
Manually tested the toString is skipped appropriately and without the need for a server restart. Ran the logging tests already in place.

### Testing Environment
Windows 10, JDK 8, Maven 3.6.3

## Documentation
Community Documentation PR:

## Notes for Reviewers
If you test this manually, fastLoggingEnabled() will return the old value while logging a logging property has been changed. Any logs after this will be using the new value. This doesn't impact the functionality but please keep it in mind if you manually test.

2021-11-08 16:28 UTC, JamesHillyard commented
Jenkins test please

2021-11-08 18:58 UTC, rdebusscher requested changes

2021-11-08 18:58 UTC, rdebusscher commented on nucleus/common/common-util/src/main/java/com/sun/common/util/logging/GFLogRecord.java
> +    private static boolean fastLoggingEnabled() {
This is slow and defeats the purpose of making logging faster.

2021-11-22 09:12 UTC, JamesHillyard commented
Jenkins test please

2021-11-22 19:07 UTC, rdebusscher reviewed
Looks good

2021-11-24 09:30 UTC, JamesHillyard commented
Jenkins test please

2021-11-24 09:30 UTC, aubi approved these changes

2021-11-24 16:36 UTC, rdebusscher approved these changes

2021-11-24 17:07 UTC, merged