FISH-5803 Added local commands option to generate-bash-autocomplete
payara/Payara pull request #5614
Opened 2022-02-17 09:24 UTC by kalinchan

## Description

Added option to generate-bash-autocomplete command to include local commands
This option is disabled by default

## Important Info
### Blockers

N/A
## Testing
### New tests

N/A
### Testing Performed

Built Payara, Started server and executed command with localCommands option set to true
### Testing Environment

Apache Maven 3.6.3
Ubuntu 20.04
openjdk version "1.8.0_302"

## Documentation

N/A
## Notes for Reviewers

I got inspiration from https://github.com/payara/Payara/blob/cf883d86b7583761e6dd35f9aa7ee4317a412f9c/nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/AdminMain.java#L262 in order to get the Local Commands. I was unable to Inject the CLIContainer to use the CLIUtil.getLocalCommands Method.

2022-02-18 10:35 UTC, Pandrex247 requested changes
Formatting, but otherwise LGTM.
Tried the following and both seemed to work:

```
payara5/bin/asadmin generate-bash-autocomplete
source payara5/glassfish/bin/bash_autocomplete
payara5/bin/asadmin st <tab>
<just shows remote commands>

payara5/bin/asadmin generate-bash-autocomplete
source payara5/glassfish/bin/bash_autocomplete --localCommands --force
payara5/bin/asadmin st <tab>
<local and remote commands displayed>
```

2022-02-18 10:35 UTC, Pandrex247 commented on nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/GenerateBashAutoCompletionCommand.java
> +    private File file;
Can we have some white space around annotated variables please? 🤢

```suggestion
    
    @Param(optional = true, primary = true, name = "file")
    String filePath;
    
    @Param(optional = true, defaultValue = "false")
    Boolean force;
    
    @Param(optional = true, defaultValue = "false")
    Boolean localCommands;
    
    @Inject
    ServiceLocator habitat;
    
    @Inject
    ServerContext serverContext;
    
    private CLIContainer cliContainer;
    private File file;
```

2022-02-18 11:24 UTC, Pandrex247 commented
Also documentation **is applicable** for this.
You've added a new option and it needs documenting: https://docs.payara.fish/community/docs/documentation/payara-server/asadmin-commands/misc-commands.html#generate-bash-autocomplete-command

2022-02-21 12:46 UTC, Pandrex247 approved these changes

2022-02-21 13:42 UTC, kalinchan commented
jenkins test please

2022-02-21 16:34 UTC, merged