FISH-898 Added timeout option to instance commands
payara/Payara pull request #5630
Opened 2022-02-28 16:53 UTC by kalinchan

## Description

Added `--timeout` option
## Important Info
### Blockers

N/A
## Testing
### New tests

N/A
### Testing Performed

Built Payara and tested timeout
### Testing Environment

ubuntu 20.04 maven 3.6.3 openjdk version "1.8.0_302"
## Documentation

https://github.com/payara/Payara-Community-Documentation/pull/296
## Notes for Reviewers

2022-02-28 16:53 UTC, kalinchan commented
jenkins test please

2022-03-02 11:33 UTC, kalinchan commented
jenkins test please

2022-03-02 13:38 UTC, Pandrex247 requested changes
I have issues with this.

I argue that this should also cover `StartLocalInstanceCommand`, `StopLocalInstanceCommand`, and `RestartLocalInstanceCommand` - they also manage the lifecycle of an instance.

I also argue that the `restart-cluster`, `start-cluster`, and `stop-cluster` commands should also have the timeout option.

I also think the way the `start-instance` command does it is a bit nicer (sidenote, we now have two different impls of how to perform a timeout) - utlising the internal managed executor service to wait after executing the command rather than spinning up a standalone unmanaged thread and executing the entire command within that.

```
    @Inject
    private PayaraExecutorService executor;
...
    /**
     * Poll for the specified amount of time to check if the instance is running.
     * Returns whether the instance was started before the timeout.
     * 
     * @return true if the instance started up, or false otherwise.
     */
    private boolean pollForLife(Server instance) {

        // Start a new thread to check when the instance has started
        CountDownLatch instanceTimeout = new CountDownLatch(1);
        ScheduledFuture<?> instancePollFuture = executor.scheduleWithFixedDelay(() -> {
            if (instance.isRunning()) {
                instanceTimeout.countDown();
            }
        }, 500, 500, MILLISECONDS);

        // If the timeout is reached, the instance isn't started so return false
        try {
            instanceTimeout.await(timeout, SECONDS);
        } catch (InterruptedException e) {
            return false;
        } finally {
            instancePollFuture.cancel(true);
        }
        
        return true;
    }
```

Also the restart-instance command timeout probably isn't working as expected. It seems to say the instance restarted successfully even if it hasn't actually restarted yet.
Running the below it reports that the instance was restarted successfully before the instance was even shut down.
```
restart-instance --timeout 1 Tender-Carp
Tender-Carp was restarted.
Command restart-instance executed successfully.
```

2022-03-21 11:06 UTC, Pandrex247 requested changes

2022-03-24 10:34 UTC, Pandrex247 requested changes
You've still got competing timeouts

2022-03-24 10:34 UTC, Pandrex247 commented on nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ClusterCommandHelper.java
> +    public void setAdminTimeout(long adminTimeout) {
Some javadoc stating that this is in milliseconds wouldn't go amiss since the timeout on the actual commands is in seconds.

2022-03-24 10:34 UTC, Pandrex247 commented on nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/RestartClusterCommand.java
> +    @Param(optional = true, defaultValue = "600")
Not sure this should have a default.
What happens now is if run these commands it the timeout will always be 10 minutes unless you specify differently, even if you've configured the global system/env property to something else.

2022-03-24 10:34 UTC, Pandrex247 commented on nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/RestartInstanceCommand.java
> +        CountDownLatch commandTimeout = new CountDownLatch(1);
Why conflicting methods of timeout for AdminCommands?
You've still got competing timeouts in this case - why not reconfigure the `READ_TIMEOUT` in `RemoteRestAdminCommand` to be configurable?

2022-03-29 13:52 UTC, Pandrex247 commented on nucleus/cluster/cli/src/main/java/com/sun/enterprise/admin/cli/cluster/RestartLocalInstanceCommand.java
> +    private int timeout;
Still got competing timeouts here.
This command calls a RemoteCLICommand which calls CLIRemoteAdminCommand, which is a child of RemoteRestAdminCommand and thus has its own timeout.

2022-03-29 13:57 UTC, Pandrex247 commented on nucleus/cluster/admin/src/main/java/fish/payara/admin/cluster/StopDeploymentGroupCommand.java
> +        if (instanceTimeout > 0) {
So it's ignored if it's not greater than 0?
Commands shouldn't just ignore incorrect parameters, they should fail.

2022-04-01 08:57 UTC, kalinchan commented
jenkins test please

2022-04-01 10:32 UTC, Pandrex247 requested changes

2022-04-01 10:32 UTC, Pandrex247 commented on nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/RestartClusterCommand.java
> +            clusterHelper.setAdminTimeout(timeout * 1000);
Overrides the usual "_timeout - 3 seconds_" behaviour and probably shouldn't

2022-04-01 10:32 UTC, Pandrex247 commented on nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/ClusterCommandHelper.java
> +        this.adminTimeout = adminTimeout;
Shouldn't this be "_timeout - 3 seconds_" (if timeout is greater than 3 seconds obviously)?
I'm wary of removing of removing this "wiggle room" that's been present for years.

2022-04-01 10:32 UTC, Pandrex247 commented on nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/StartClusterCommand.java
> +            clusterHelper.setAdminTimeout(timeout * 1000);
Overrides the usual "_timeout - 3 seconds_" behaviour and probably shouldn't

2022-04-01 10:32 UTC, Pandrex247 commented on nucleus/cluster/admin/src/main/java/com/sun/enterprise/v3/admin/cluster/StopClusterCommand.java
> +            clusterHelper.setAdminTimeout(timeout * 1000);
Overrides the usual "_timeout - 3 seconds_" behaviour and probably shouldn't

2022-04-01 10:32 UTC, Pandrex247 commented on nucleus/cluster/admin/src/main/java/fish/payara/admin/cluster/RestartDeploymentGroupCommand.java
> +                clusterHelper.setAdminTimeout(timeout * 1000);
Overrides the usual "_timeout - 3 seconds_" behaviour and probably shouldn't

2022-04-01 10:32 UTC, Pandrex247 commented on nucleus/cluster/admin/src/main/java/fish/payara/admin/cluster/StartDeploymentGroupCommand.java
> +            clusterHelper.setAdminTimeout(timeout * 1000);
Overrides the usual "_timeout - 3 seconds_" behaviour and probably shouldn't

2022-04-01 10:32 UTC, Pandrex247 commented on nucleus/cluster/admin/src/main/java/fish/payara/admin/cluster/StopDeploymentGroupCommand.java
> +            clusterHelper.setAdminTimeout(Integer.valueOf(timeout) * 1000);
Overrides the usual "_timeout - 3 seconds_" behaviour and probably shouldn't

2022-04-01 10:32 UTC, Pandrex247 commented on nucleus/admin/util/src/main/java/com/sun/enterprise/admin/util/TimeoutParamDefaultCalculator.java
> +
```suggestion
```
(╯°□°）╯︵ ┻━┻

2022-04-01 10:32 UTC, Pandrex247 commented on nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/LocalServerCommand.java
>          // timeout at runtime.
```suggestion
```
Today is that day

2022-04-01 10:32 UTC, Pandrex247 commented on nucleus/admin/cli/src/main/java/com/sun/enterprise/admin/cli/remote/RemoteCLICommand.java
> +            if(readTimeout > 0){
```suggestion
            if (readTimeout > 0){
```
(╯°□°）╯︵ ┻━┻

2022-04-04 11:29 UTC, Pandrex247 approved these changes

2022-04-04 11:30 UTC, Pandrex247 commented
Jenkins test please

2022-04-04 13:30 UTC, merged