FISH-6043 Configuring Payara Notification Logging Service causes NullPointerException
payara/Payara pull request #5646
Opened 2022-03-09 16:47 UTC by arieki

## Description

Bug fixed the Payara notification logging service configuration 

## Important Info
### Blockers

N/A

## Testing
### New tests

N/A

### Testing Performed
Start the server and configure the Notification Service to use a separate log file and update any of the Payara Notification Logging Service logger settings

### Testing Environment
Windows 11, JDK 8

## Documentation
N/A

## Notes for Reviewers
N/A

2022-03-09 16:47 UTC, arieki commented
Jenkins test please

2022-03-09 16:55 UTC, arieki commented
jenkins test please

2022-03-10 11:31 UTC, kalinchan requested changes
nucleus/core/logging/src/main/java/fish/payara/enterprise/server/logging/PayaraNotificationFileHandler.java copyright needs updating

2022-03-10 16:10 UTC, kalinchan requested changes

2022-03-11 00:08 UTC, arieki commented
jenkins test please

2022-03-11 09:24 UTC, merged