FISH-6006 Upgrade Jakarta Authentication API to 3.0.0
payara/Payara pull request #5786
Opened 2022-06-02 15:02 UTC by jGauravGupta

Jakarta Authentication TCK 3.0.0 Test result :
````
[INFO] Jakarta Authentication TCK - common 1.0-SNAPSHOT ... SUCCESS [  3.386 s]
[INFO] Jakarta Authentication TCK - main 3.0.0 ............ SUCCESS [ 22.418 s]
[INFO] Jakarta Authentication TCK - basic-authentication 3.0.0 SUCCESS [ 34.695 s]
 Tests run: 8, Failures: 0, Errors: 0, Skipped: 0
[INFO] Jakarta Authentication TCK - custom principal 3.0.0  SUCCESS [ 32.066 s]
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0
[INFO] Jakarta Authentication TCK - programmatic-authentication 3.0.0 SUCCESS [ 29.355 s]
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
[INFO] Jakarta Authentication TCK - lifecycle 3.0.0 ....... SUCCESS [ 32.625 s]
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
[INFO] Jakarta Authentication TCK - wrapping 3.0.0 ........ SUCCESS [ 30.912 s]
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0
[INFO] Jakarta Authentication TCK - register-session 3.0.0  SUCCESS [ 33.401 s]
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
[INFO] Jakarta Authentication TCK - async-authentication 3.0.0 SUCCESS [ 34.279 s]
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] Jakarta Authentication TCK - status-codes 3.0.0 .... SUCCESS [ 32.111 s]
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[INFO] Jakarta Authentication TCK - dispatching 3.0.0 ..... SUCCESS [ 32.560 s]
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
[INFO] Jakarta Authentication TCK - dispatching JSF CDI 3.0.0 SUCCESS [ 40.207 s]
 Tests run: 9, Failures: 0, Errors: 0, Skipped: 0
[INFO] Jakarta Authentication TCK - ejb-propagation 3.0.0 . SUCCESS [ 38.561 s]
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
[INFO] Jakarta Authentication TCK - ejb-register-session 3.0.0 SUCCESS [ 38.060 s]
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[INFO] Jakarta Authentication TCK - authorization-propagation 3.0.0 SUCCESS [ 37.440 s]
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
[INFO] Jakarta Authentication TCK - invoke EJB and CDI 3.0.0 SUCCESS [ 53.647 s]
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0
````
### TCK Runner:
https://github.com/payara/jakartaee-10-tck-runners/pull/10

2022-06-02 15:04 UTC, jGauravGupta commented
jenkins test please

2022-06-03 04:07 UTC, breakponchito approved these changes
LGTM

2022-06-03 12:42 UTC, pdudits requested changes

2022-06-03 12:42 UTC, pdudits commented on appserver/security/jaspic-provider-framework/src/main/java/com/sun/jaspic/config/factory/AuthConfigFileFactory.java
>   *
Unused import

2022-06-03 12:42 UTC, pdudits commented on appserver/packager/external/jakarta-ee9-shim/pom.xml
> +                                    jakarta.interceptor-api,
duplicate bundle name for interceptor, I think eclipselink and Moxy are not necessary after ugprade to 4.0 that we completed in the meantime.

2022-06-06 10:30 UTC, jGauravGupta commented
jenkins test please

2022-06-06 11:27 UTC, jGauravGupta commented
jenkins test please

2022-06-07 08:03 UTC, jGauravGupta commented
jenkins test please

2022-06-07 10:23 UTC, merged