Fish 5722 mes in payara resources xml
payara/Payara pull request #5798
Opened 2022-06-08 19:45 UTC by aubi

## Description
Allow definition of concurrency resources to be defined in payara-resources.xml

## Testing
### New tests
Added test in appserver/tests/payara-samples/samples/resources/mes-in-payara-resources-example

### Testing Environment
OpenJDK, Linux

## Documentation
TBD

2022-06-08 19:46 UTC, aubi commented
Jenkins test please

2022-06-09 09:52 UTC, aubi commented
Jenkins test please

2022-06-09 12:11 UTC, aubi commented
Jenkins test please

2022-06-14 14:30 UTC, Pandrex247 commented on appserver/connectors/descriptors/src/main/resources/glassfish/lib/dtds/payara-resources_1_6.dtd
> +    | connector-connection-pool | work-security-map
Hmm, I wonder if we should be making a 1.7 DTD for this.

2022-06-14 15:57 UTC, Pandrex247 requested changes

2022-06-14 15:57 UTC, Pandrex247 commented on appserver/resources/resources-connector/src/main/java/org/glassfish/resources/admin/cli/ResourcesXMLParser.java
> +        }
Duplicate of 749-752?

2022-06-14 15:57 UTC, Pandrex247 commented on appserver/resources/resources-connector/src/main/java/org/glassfish/resources/admin/cli/ResourcesXMLParser.java
> +        }
Duplicate of 843-847?

2022-06-16 20:39 UTC, aubi commented
Jenkins test please

2022-06-17 08:43 UTC, Pandrex247 requested changes
Missed a duplicate block

2022-06-17 08:43 UTC, Pandrex247 commented on appserver/resources/resources-connector/src/main/java/org/glassfish/resources/admin/cli/ResourcesXMLParser.java
> +        }
Not resolved?
```suggestion
```

2022-06-17 08:58 UTC, aubi commented
Jenkins test please

2022-06-17 09:00 UTC, Pandrex247 approved these changes

2022-06-17 10:49 UTC, merged