[QACI-716 QACI-718] - PRTestPipeline - Community 5
payara/Payara pull request #5826
Opened 2022-06-28 08:47 UTC by cubastanley

## Description
Creates a barebones pipeline with config for execution using modular pipeline components

## Important Info
### Blockers
Requires shift to Payara Test Library in Jenkins **[PENDING]**

## Documentation
_TBC_

2022-06-28 09:13 UTC, cubastanley commented
Jenkins test

2022-07-06 09:25 UTC, cubastanley commented
Modules within code base are successful and working - now pending external suite modules before merge

2022-07-06 11:23 UTC, Pandrex247 requested changes

2022-07-06 11:23 UTC, Pandrex247 commented on .jenkins/modules/Test/PayaraSamplesTest.groovy
> +        -Dpayara.version=${CFG.'build.version'} \
`-Dpayara.home` needs to be set.

2022-07-13 11:10 UTC, cubastanley commented
Jenkins test please

2022-07-13 11:21 UTC, Pandrex247 approved these changes

2022-07-14 08:10 UTC, merged