FISH-6392: upgrading npn grizzly dependency to test payara server 6
payara/Payara pull request #5845
Opened 2022-07-14 02:02 UTC by breakponchito

Improve memory for alpn negotiator maps
## Description

This PR is to test the jenkins pipeline and verify the whole tests are passing after changing the grizzly npn dependency
## Important Info
### Blockers

## Testing
### New tests

### Testing Performed

Manual testing
### Testing Environment

Windows 11, Azul JDK 11, Maven 3.8.3
## Documentation

## Notes for Reviewers

2022-07-14 02:02 UTC, breakponchito commented
Jenkins test please

2022-07-26 10:32 UTC, Pandrex247 requested changes

2022-07-26 10:32 UTC, Pandrex247 commented on nucleus/pom.xml
> +        <grizzly.npn.api.version>2.0.1</grizzly.npn.api.version>
We're using a patched version.
```suggestion
        <grizzly.npn.api.version>2.0.0.payara-p1</grizzly.npn.api.version>
```

2022-08-01 11:05 UTC, Pandrex247 commented
Jenkins test please

2022-08-01 12:51 UTC, merged