FISH-6238 Microprofile Interceptors [@Fallback@/CircuitBreaker] are not getting invoked if the EJB is a @Stateless Bean
payara/Payara pull request #5933
Opened 2022-09-09 02:11 UTC by arieki

## Description

This is a fix for https://github.com/payara/Payara/issues/5679 issue.
Session bean failed to recognize programmatic interceptor regarding fault-tolerance interceptor that is using around invoke interception type

## Important Info
### Blockers

N/A

## Testing
### New tests

None

### Testing Performed

+ Build payara server with build extras profile `-PBuildExtras`
+ Checkout this reproducer https://github.com/ismailsalloo/payara-sample
+ Change version of `fish.payara.extras:payara-embedded-all` payara-sample's dependency to appropriate `payara-embedded-all` version which is `5.2022.4-SNAPSHOT`
example:
```
<dependency>
  <groupId>fish.payara.extras</groupId>
  <artifactId>payara-embedded-all</artifactId>
  <version>5.2022.4-SNAPSHOT</version>
  <scope>test</scope>
</dependency>
```
+ Run `mvn clean test` 

### Testing Environment

Windows 11, OpenJDK1.8, Maven 3.8.4

## Documentation

None

## Notes for Reviewers

None

2022-09-09 02:13 UTC, arieki commented
jenkins test please

2022-09-09 02:55 UTC, arieki commented
jenkins test please

2022-09-09 07:43 UTC, pdudits requested changes
This doesn't fix invocation of programmatic interceptors on EJBs.

It only fixes invocation of programmatic interceptors that happen to have method called `intercept(InvocationContext)`, and their `Interceptor.intercept` definition calls this method without further logic.

`FaultoreanceExtension.ProgrammaticInterceptor` happens to be such.

We instead should be able to define descriptor is a way, that `Interceptor.intercept(type, instance, ctx` would be called rather than looking for an annotated method.

2022-09-12 10:00 UTC, arieki commented
jenkins test please

2022-09-12 12:23 UTC, arieki commented
> This doesn't fix invocation of programmatic interceptors on EJBs.
> 
> It only fixes invocation of programmatic interceptors that happen to have method called `intercept(InvocationContext)`, and their `Interceptor.intercept` definition calls this method without further logic.
> 
> `FaultoreanceExtension.ProgrammaticInterceptor` happens to be such.
> 
> We instead should be able to define descriptor is a way, that `Interceptor.intercept(type, instance, ctx` would be called rather than looking for an annotated method.

As discussed, I am using `aroundInvoke` annotation as a workaround solution since it needs deeper analysis on how to combine CDI interceptor that implemented programmatically with EJB interceptor

2022-09-12 16:40 UTC, arieki commented
jenkins test please

2022-09-13 08:22 UTC, pdudits approved these changes

2022-09-13 11:07 UTC, arieki commented
jenkins test please

2022-09-14 05:10 UTC, arieki commented
jenkins test please

2022-09-14 07:30 UTC, merged