FISH-6697 Update Metro to 2.4.8 and Woodstox 6.4.0
payara/Payara pull request #6072
Opened 2022-11-23 07:01 UTC by arieki

woodstox upgrade is required because metro-jax-ws is using 6.x.x version

Signed-off-by: Arie Kiswanto <arie.kiswanto@payara.fish>

## Description

Metro upgrade to 2.4.8.payara-p1
Woodstox upgrade to 6.4.0

## Important Info
### Blockers

https://github.com/payara/patched-src-metro-wsit/pull/17 - metro re-apply patches
https://github.com/payara/patched-src-metro-jax-ws/pull/7 - metro-jax-ws re-apply patches

## Testing
### New tests

None

### Testing Performed

Build and run payara server
Run payara samples and quicklook test

### Testing Environment

Windows 11, WSL, OpenJDK8, Maven 3.8.6

## Documentation

None

## Notes for Reviewers

None

2022-11-23 07:45 UTC, svendiedrichsen commented on appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/WSClientContainer.java
> +           (spiType == com.sun.xml.ws.assembler.metro.dev.ClientPipelineHook.class)){
This second one looks redundant.

2022-11-28 13:08 UTC, Pandrex247 requested changes
Please update Third Party License.
https://github.com/payara/Payara/blob/master/appserver/packager/legal/src/main/resources/glassfish/legal/3RD-PARTY-LICENSE.txt#L58

2022-11-28 13:08 UTC, Pandrex247 commented on appserver/security/webservices.security/src/main/java/com/sun/enterprise/security/webservices/SecurityServiceImpl.java
> +// Portions Copyright [2018, 2019, 2022] [Payara Foundation and/or its affiliates]
```suggestion
// Portions Copyright [2018-2022] [Payara Foundation and/or its affiliates]
```

2022-11-28 13:08 UTC, Pandrex247 commented on appserver/webservices/jsr109-impl/src/main/java/org/glassfish/webservices/SecurityService.java
> +// Portions Copyright [2018, 2022] [Payara Foundation and/or its affiliates]
```suggestion
// Portions Copyright [2018-2022] [Payara Foundation and/or its affiliates]
```

2022-11-28 13:08 UTC, Pandrex247 commented on appserver/security/webservices.security/src/main/java/com/sun/enterprise/security/webservices/ClientPipeCreator.java
> +// Portions Copyright [2018, 2022] [Payara Foundation and/or its affiliates]
Usual format is with a hyphen, not commas
```suggestion
// Portions Copyright [2018-2022] [Payara Foundation and/or its affiliates]
```

2022-11-29 09:12 UTC, Pandrex247 approved these changes

2022-11-29 09:12 UTC, merged