FISH-1413 (P6) Perform variable substitution for create-connector-connection-pool
payara/Payara pull request #6121
Opened 2022-12-16 13:01 UTC by JamesHillyard

## Description
When the `create-connector-connection-pool` command is executed currently it fails when environment variables are used as there is no substitution in place. With this change before the properties are set a full variable replacement check is performed.

## Important Info

## Testing
### Testing Performed
Started the server, set the NUM environment variable to 20, ran the relevant command below:

**Windows (cmd)**
 `asadmin create-connector-connection-pool --connectiondefinition=jakarta.jms.ConnectionFactory --transactionSupport=NoTransaction --resourceAdapterName=jmsra --maxpoolsize=${ENV=NUM}`

**Windows (Windows Terminal / Poweshell)**
_Remove the spaces in ${ENV=NUM} - These were necessary to keep the backticks_ 
``asadmin create-connector-connection-pool --connectiondefinition=jakarta.jms.ConnectionFactory --transactionSupport=NoTransaction --resourceAdapterName=jmsra --maxpoolsize=`$` {ENV=NUM` }``

**Linux**
`asadmin create-connector-connection-pool --connectiondefinition=jakarta.jms.ConnectionFactory --transactionSupport=NoTransaction --resourceAdapterName=jmsra --maxpoolsize=\${ENV=NUM}`

### Testing Environment
Windows 10, Ubuntu 20.04 (WSL), Maven 3.6.3, Zulu JDK 11

## Documentation
Coming soon...

## Notes for Reviewers
Using proper escaping is important depending on the terminal / OS you are using.
**Windows CMD**: No escaping required
**Windows Powershell / Windows Terminal**: Escape $ and { } characters with a backtick
**Linux**: Escape $ with a backslash

2022-12-16 13:01 UTC, JamesHillyard commented
Jenkins test please

2022-12-29 01:41 UTC, luiseufrasio requested changes
Did not work for my local test:

C:\Users\luise\git\Payara>git status
On branch FISH-1413-P6
Your branch is up to date with 'origin/FISH-1413-P6'.

nothing to commit, working tree clean

C:\Users\luise\git\Payara>set NUM=20

C:\Users\luise\git\Payara>echo %NUM%
20

C:\Users\luise\git\Payara>.\appserver\distributions\payara\target\stage\payara6\bin\asadmin create-connector-connection-pool --connectiondefinition=jakarta.jms.ConnectionFactory --transactionSupport=NoTransaction --resourceAdapterName=jmsra --maxpoolsize=${ENV=NUM}
Enter the value for the poolname operand> testPool
**remote failure: Connector connection pool testPool creation failed. HV000028: Unexpected exception during isValid call.
Command create-connector-connection-pool failed.**

2023-01-06 00:03 UTC, breakponchito commented
this is working fine following next steps:

- open CMD
- set environment variable
- start payara on the same CMD console without verbose option
- execute command

`
C:\java\projects\Payara\appserver\distributions\payara\target\stage\payara6\bin>asadmin create-connector-connection-pool --connectiondefinition=jakarta.jms.ConnectionFactory --transactionSupport=NoTransaction --resourceAdapterName=jmsra --maxpoolsize=${ENV=NUM}
Enter the value for the poolname operand> testPool
Connector connection pool testPool created.
Command create-connector-connection-pool executed successfully
`

2023-01-06 00:04 UTC, breakponchito approved these changes
LGTM

2023-01-09 13:45 UTC, merged