FISH-6970 FISH-6973: App-specific OpenTelemetry configuration and integration
payara/Payara pull request #6192
Opened 2023-02-09 09:35 UTC by pdudits

## Description

An application can configure its OpenTelemetry SDK using microprofile config properties with prefix `otel.` using [AutoConfigure Facility](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md).
To enable the feature `otel.sdk.disabled=false` need to be set (as per MP spec).

In such case OpenTelemetry is enabled regardless of request tracing service state.
If Request Tracing is enabled and application requests opentelemetry, all traces are also exported to Request Tracing Service.
OpenTelemetry is enabled always when Request Tracing is enabled and uses standard same autoconfigure facility, using system properties and environment variables.

OpenTelemetry types are injectable as per MP spec.

Previous Tracer implementation is deprecated and it is not used anywhere now, can soon be removed.

## Important Info
### Blockers

## Testing
### New tests

Passes 9/12 test cases of OpenTelemetry Tracing TCK. That includes REST endpoint instrumentation which is still done over opentracing shim (!). The failures however show that we'll need to redo that tracing in opentelemetry, because asserted trace metadata cannot be set via shim.

### Testing Performed

MP OpenTracing passes, as well as propagation-related payara-samples

### Testing Environment

```
Java version: 11.0.17, vendor: Azul Systems, Inc., runtime: C:\Program Files\Zulu\zulu-11
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
```

## Documentation

Not yet, but there will be major changes, as support for custom opentracing tracers will also go away.

2023-02-09 09:35 UTC, pdudits commented
Jenkins test please

2023-02-09 18:43 UTC, pdudits commented
Jenkins test please

2023-02-09 18:49 UTC, pdudits commented
Jenkins test please
```
The injected Tracer is required to be an instance of io.opentracing.mock.MockTracer but is instead
an instance of io.opentracing.mock.MockTracer@6ac6f51b
```
We need tracer to be in dependent scope for opentracing-mock to work.

2023-02-13 12:40 UTC, Pandrex247 requested changes
I keep getting this error, is this something that we can control? We don't seem to have any documentation for OpenTelemetry over in our docs.
`[#|2023-02-13T12:28:54.883+0000|SEVERE|Payara 6.2023.3-SNAPSHOT|io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter|_ThreadID=661;_ThreadName=OkHttp http://localhost:4317/...;_TimeMillis=1676291334883;_LevelValue=1000;|
  Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/0:0:0:0:0:0:0:1:4317|#]`

Also you missed adding OpenTelemetry (and so by extension presumably OkHttp) to `3RD-PARTY-LICENSE.txt`

2023-02-13 13:08 UTC, pdudits commented on appserver/payara-appserver-modules/pom.xml
> -        <module>opentracing-cdi</module>
The error means is that it has no opentelemetry endpoint to report to. It only happens when tracing is enabled, and we will advise to actually trace with external tool (or configure exporter to None).

I'll kill the remains of the module and have a look at license.

2023-02-14 13:12 UTC, pdudits commented
Added commits that finalize the implementation, fix cases where server was failing with tracing service turned on while also addressed your comments.

This version will not work without https://github.com/payara/MicroProfile-TCK-Runners/pull/212, because using external opentracing implementations is no longer possible.

2023-02-15 06:34 UTC, arieki commented
jenkins test please

2023-02-15 07:16 UTC, arieki commented
> jenkins test please

sorry I forgot MP TCK Runner haven't merged yett

2023-02-15 12:14 UTC, Pandrex247 approved these changes
I assume we'll have some documentation around this new log message (touch to configure, don't touch - bears):

`AutoConfiguredOpenTelemetrySdk found on classpath but automatic configuration is disabled. To enable, run your JVM with -Dotel.java.global-autoconfigure.enabled=true`

Other than that seems good!

Disclaimer: I haven't tested trying to use it with Jaeger or other OpenTracing impls we previously worked with

2023-02-15 12:16 UTC, pdudits commented
Yes, we'll have to flip a coin on what to do in this case, when something touches globally configured telemetry. We'll probably force it to NoOp now, so it remains silent. But let's wait until we've got the entire package in.

2023-02-20 08:14 UTC, pdudits commented
Jenkins test please

2023-02-20 13:20 UTC, pdudits commented
Jenkins test please

2023-02-20 14:17 UTC, pdudits commented
Jenkins test please

2023-02-21 08:11 UTC, pdudits commented
Jenkins test please

2023-02-21 12:36 UTC, pdudits commented
Jenkins test please

2023-02-21 15:50 UTC, merged