FISH-6971 Instrument JAX-RS endpoints in OTEL-enabled application
payara/Payara pull request #6209
Opened 2023-02-21 17:20 UTC by arieki

## Description

Enable OpenTelemetry on JAX-RS server-side

## Important Info
### Blockers

N/A

## Testing
### New tests

N/A

### Testing Performed

Build and run Payara server, execute MP OpenTelemetry TCK and MP Opentracing TCK

### Testing Environment

Windows 11, OpenJDK11, Maven 3.8.4

## Documentation

## Notes for Reviewers

To be able to execute MP OpenTelemetry TCK there is one adjustment that needs to do which is enabling `JerseyOpenTelemetryAutoDiscoverable` to be automatically discovered by JAX-RS runtime. This is necessary because when I enable OpenTelemetry by default, Payara server loose compatibility with opentracing spec

2023-02-21 17:21 UTC, arieki commented
jenkins test please

2023-02-22 09:30 UTC, pdudits requested changes
I'll do more throughout review when I check out the branch.

It is heading in right direction, we might need to make configuration more consistent and don't make TCK-specific workarounds. If anything, those should be configurable in TCK runner.

2023-02-23 14:22 UTC, pdudits commented on appserver/payara-appserver-modules/jaxrs-client-tracing/pom.xml
> +<!--        </dependency>-->
Remove it in next PR, please

2023-02-23 14:22 UTC, pdudits approved these changes

2023-02-23 15:13 UTC, arieki commented
jenkins test please

2023-02-23 16:50 UTC, merged