FISH-6504 Load cacerts.jks if p12 is not Found
payara/Payara pull request #6272
Opened 2023-04-26 11:33 UTC by aubi

During verification of master password, load `cacerts.jks` if `cacerts.p12` is not found

## Description
After the transition to key/truststores to P12 format, server doesn't start if the stores are in JKS.
This change allows to start the server and serve HTTPS.

## Testing
### Testing Performed

After building this PR, replace both *.p12 files in `appserver/distributions/payara/target/stage/payara6/glassfish/domains/domain1/config` (`cacerts` and `keystore`) with their jks version (e.g. from Payara 5 build).
Also change the names in `domain.xml`:
```
<jvm-options>-Djavax.net.ssl.keyStore=${com.sun.aas.instanceRoot}/config/keystore.jks</jvm-options>
```
Start the server normally and try all ports: 8080, 8181, 4848

### Testing Environment
OpenJDK 11, Linux

2023-04-26 13:04 UTC, aubi commented
jenkins test please

2023-04-26 13:19 UTC, Pandrex247 requested changes

2023-04-26 13:19 UTC, Pandrex247 commented on nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/LocalServerCommand.java
> +                        new File(configDir, DomainConstants.TRUSTSTORE_JSK_FILE))
(╯°□°）╯︵ ┻━┻
```suggestion
                        new File(configDir, DomainConstants.TRUSTSTORE_JKS_FILE))
```

2023-04-26 13:19 UTC, Pandrex247 commented on nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/domain/DomainConstants.java
> +    public static final String TRUSTSTORE_JSK_FILE = "cacerts.jks";
(╯°□°）╯︵ ┻━┻
```suggestion
    public static final String TRUSTSTORE_JKS_FILE = "cacerts.jks";
```

2023-04-26 13:19 UTC, Pandrex247 commented on nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/domain/DomainConstants.java
Copyright

2023-04-26 13:19 UTC, Pandrex247 commented on nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/cli/LocalServerCommand.java
Copyright

2023-04-26 13:19 UTC, Pandrex247 commented on nucleus/admin/server-mgmt/src/main/java/fish/payara/admin/servermgmt/cli/AddKeypairCommand.java
Copyright

2023-04-26 15:18 UTC, aubi commented
jenkins test please

2023-04-28 11:08 UTC, Pandrex247 approved these changes

2023-04-28 12:12 UTC, merged