FISH-7409: adding property to load com.sun.jndi.ldap classes for jdk 17
payara/Payara pull request #6345
Opened 2023-07-25 05:07 UTC by breakponchito

Adding fix to include com.sun.jndi.ldap classes when using jdk 17
## Description

This is a fix of a reported bug when trying to use jndi.ldap classes
## Important Info
### Blockers

## Testing
### New tests

### Testing Performed

Manual testing:
Now the call of the endpoint is responding with 200:

![image](https://github.com/payara/Payara/assets/279375/b9446d8a-efd6-498f-8624-1a2ea01154e6)

### Testing Environment

Ubuntu 20.04, maven 3.8.6, azul jdk 17
## Documentation

## Notes for Reviewers

2023-07-25 05:08 UTC, breakponchito commented
Jenkins test please

2023-07-25 08:05 UTC, Pandrex247 commented on appserver/admin/production_domain_template/src/main/resources/config/domain.xml
Don't you also need to add to the default-config in this file too?

2023-07-25 08:05 UTC, Pandrex247 commented on appserver/admin/production_domain_template/src/main/resources/config/domain.xml
Copyright

2023-07-25 08:06 UTC, Pandrex247 commented on appserver/admin/gf_template_web/src/main/resources/config/domain.xml
Copyright

2023-07-25 08:06 UTC, Pandrex247 commented on appserver/admin/gf_template/src/main/resources/config/domain.xml
Copyright

2023-07-25 08:06 UTC, Pandrex247 commented on appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml
Copyright

2023-07-25 15:12 UTC, breakponchito commented on appserver/admin/production_domain_template/src/main/resources/config/domain.xml
yes you are right, already added

2023-07-25 15:12 UTC, breakponchito commented on appserver/admin/production_domain_template/src/main/resources/config/domain.xml
done

2023-07-25 15:12 UTC, breakponchito commented on appserver/admin/production_domain_template_web/src/main/resources/config/domain.xml
done

2023-07-25 15:14 UTC, breakponchito commented
Jenkins test please

2023-07-26 16:05 UTC, Pandrex247 submitted a review, later dismissed

2023-07-26 16:08 UTC, Pandrex247 requested changes

2023-07-26 16:08 UTC, Pandrex247 commented on appserver/admin/gf_template_web/src/main/resources/config/domain.xml
You've missed adding the option to the default-config block

2023-07-26 16:16 UTC, breakponchito commented on appserver/admin/gf_template_web/src/main/resources/config/domain.xml
already added

2023-07-26 16:16 UTC, Pandrex247 approved these changes

2023-07-26 21:23 UTC, merged