FISH-7044: preventing the addition of multiple HSTS header for response
payara/Payara pull request #6366
Opened 2023-08-17 03:41 UTC by breakponchito

## Description

## Important Info
### Blockers

## Testing
### New tests

### Testing Performed

### Testing Environment

## Documentation

## Notes for Reviewers

2023-08-17 03:41 UTC, breakponchito commented
Jenkins test please

2023-08-17 04:13 UTC, breakponchito commented
Jenkins test please

2023-08-17 14:30 UTC, breakponchito commented
Jenkins test please

2023-08-18 12:18 UTC, Pandrex247 approved these changes

2023-08-18 12:19 UTC, Pandrex247 requested changes

2023-08-18 12:19 UTC, Pandrex247 commented on nucleus/grizzly/config/src/main/java/org/glassfish/grizzly/config/HSTSFilter.java
Copyright needs updating

2023-08-18 16:04 UTC, Pandrex247 approved these changes

2023-08-18 17:09 UTC, merged