FISH-7647 : Port Fixes for CVE-2017-12617
payara/Payara pull request #6374
Opened 2023-08-23 00:41 UTC by luiseufrasio

## Description
Port Fixes for CVE-2017-12617

## Important Info
### Blockers
None

## Testing
### New tests
None

### Testing Performed

### Testing Environment
Zulu JDK 11.0.11 on Windows 11 with Maven 3.8.4

## Documentation
None

## Notes for Reviewers
It was avoided to use normalize function in basePath and canonicaPath because it was causing NullPointerException in DAS loading at runtime.

2023-08-24 14:39 UTC, luiseufrasio commented
jenkins test please

2023-08-31 17:42 UTC, luiseufrasio commented
jenkins test please

2023-09-01 11:22 UTC, Pandrex247 requested changes

2023-09-04 00:54 UTC, luiseufrasio commented on appserver/web/web-naming/src/main/java/org/apache/naming/resources/FileDirContext.java
>          this.absoluteBase = base.getAbsolutePath();
done

2023-09-04 00:55 UTC, luiseufrasio commented
jenkins test please

2023-09-04 08:29 UTC, Pandrex247 approved these changes

2023-09-04 08:29 UTC, merged