Github action to automate additional Community Supporting Processes
payara/Payara pull request #6376
Opened 2023-08-23 17:07 UTC by RamyaBill

This is the PR to automate additional community supporting process as detailed in the below Jira issues -

- https://payara.atlassian.net/browse/SERV-1005
- https://payara.atlassian.net/browse/SERV-1006

2023-08-24 08:04 UTC, JamesHillyard commented
Jenkins test please

2023-09-05 22:09 UTC, fturizo requested changes
Changes needed

2023-09-05 22:09 UTC, fturizo commented on .github/workflows/monitor-inactive-openissues.yml
> +                  body: updateMessage,
As agreed, it is better to replace this action with an MS Teams message instead.

2023-09-21 18:45 UTC, fturizo approved these changes
@RamyaBill, I have implemented the changes we discussed.

2023-09-21 18:58 UTC, merged