FISH-8062 Third Party License Generation
payara/Payara pull request #6514
Opened 2023-12-28 12:14 UTC by kalinchan

## Documentation

Build Payara and then execute the following `mvn license:download-licenses license:aggregate-add-third-party`
## Notes for Reviewers

Phase is null due to the relative path for submodules being incorrect when building payara

2024-01-08 10:13 UTC, Pandrex247 requested changes

2024-01-08 10:13 UTC, Pandrex247 commented on nucleus/osgi-platforms/felix/pom.xml
> +                <version>2.3.0</version>
Version not required, it's defined in `pluginManagement`

2024-01-08 10:13 UTC, Pandrex247 commented on nucleus/pom.xml
> +                <version>2.3.0</version>
Version not required, it's defined in `pluginManagement`

2024-01-08 10:13 UTC, Pandrex247 commented on pom.xml
> +                    <version>2.3.0</version>
I'd prefer if this was defined as a property.

2024-01-08 10:13 UTC, Pandrex247 commented on api/pom.xml
> +                <version>2.3.0</version>
Version not required, it's defined in `pluginManagement`

2024-01-08 10:13 UTC, Pandrex247 commented on appserver/packager/legal/src/main/resources/glassfish/legal/3RD-PARTY-LICENSE.txt
This doesn't seem to be autogenerated?
If I change a dependency version and rebuild the server the file still shows the old version

2024-01-10 09:21 UTC, Pandrex247 commented on appserver/packager/legal/src/main/resources/glassfish/legal/3RD-PARTY-LICENSE.txt
Is there a reason we're hiding it behind a profile?

2024-01-10 12:13 UTC, kalinchan commented on appserver/packager/legal/src/main/resources/glassfish/legal/3RD-PARTY-LICENSE.txt
Removed from profile

2024-01-15 11:46 UTC, Pandrex247 requested changes
Can we add the 3RD-PARTY-LICENSE file to gitignore?
Does it need to be there at all?

After changing a version property (e.g. jackson 2.15.0 to 2.16.1) and building the server it shows the file as having changed in git

2024-01-16 14:18 UTC, Pandrex247 approved these changes

2024-01-17 09:34 UTC, merged