FISH-8208 : year in index.html updated
payara/Payara pull request #6531
Opened 2024-01-18 20:35 UTC by luiseufrasio

## Description
Update copyright year in Payara's default index.html

## Important Info
### Blockers
none

## Testing
### New tests
none

### Testing Performed
1. Build Payara Server
2. Run Payara Server
3. Poke http://localhost:8080/
4. Copyright 2024 should appear at the bottom of the page

### Testing Environment
Zulu JDK 11 on Windows 11 with Maven 3.8.6

## Documentation
None

2024-01-18 20:35 UTC, luiseufrasio commented
jenkins test please

2024-01-19 09:17 UTC, Pandrex247 approved these changes

2024-01-19 09:18 UTC, Pandrex247 requested changes
We probably also need to update the copyright on https://github.com/payara/Payara/blob/91c42a958d2c2e9d7cdf0a6136c41fcbd87a0c87/appserver/admingui/payara-theme/src/main/resources/org/glassfish/admingui/community-theme/Strings.properties

2024-01-19 11:07 UTC, luiseufrasio commented
jenkins test please

2024-01-19 11:10 UTC, Pandrex247 approved these changes

2024-01-20 23:55 UTC, merged