FISH-8216 : codehaus.mojo replaced by omnifaces as in Glassfish
payara/Payara pull request #6536
Opened 2024-01-24 12:38 UTC by luiseufrasio

## Description
The Security Manager is deprecated and will be removed in a future release

## Important Info
### Blockers
None

## Testing
### New tests
None

### Testing Performed
Samples, quicklook etc

### Testing Environment
Zulu JDK 11.0.11 on Windows 11 with Maven 3.8.6

## Documentation
None

## Notes for Reviewers
None

2024-01-24 13:52 UTC, Pandrex247 requested changes
Probably also need to change the groupId of the plugin defined in `<pluginManagement>` in core/core-parent/pom.xml (and update its version if appropriate)

2024-01-24 13:52 UTC, Pandrex247 commented on appserver/persistence/cmp/support-ejb/pom.xml
Copyright needs updating

2024-01-24 13:52 UTC, Pandrex247 commented on appserver/persistence/cmp/support-sqlstore/pom.xml
Copyright needs updating

2024-01-30 18:14 UTC, luiseufrasio commented on appserver/persistence/cmp/support-ejb/pom.xml
done

2024-01-31 09:07 UTC, Pandrex247 approved these changes

2024-01-31 12:29 UTC, merged