FISH-7868 Increase System Properties Length to 4096 Characters
payara/Payara pull request #6551
Opened 2024-02-01 15:10 UTC by aubi

## Description
The current maximum length is 512, which can be very short for some setups. The new length is 4096.

## Testing
### Testing Performed
Go to AdminUI, Configuration, System Properties and try to create a property `X` with value
```
1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
```
E.g. 1.000 characters. Then save the value and copy the value back to some text editor. Verify, that the new value has 1.000 characters.

I increased also length for description as it can serve to store alternate value.

### Testing Environment
Linux, OpenJDK 11

2024-02-02 13:49 UTC, breakponchito approved these changes
LGTM

2024-02-05 09:26 UTC, Pandrex247 requested changes

2024-02-05 09:26 UTC, Pandrex247 commented on appserver/admingui/common/src/main/resources/org/glassfish/common/FieldLengths.properties
Copyright needs updating

2024-02-05 09:34 UTC, Pandrex247 approved these changes

2024-02-05 11:53 UTC, merged