FISH-8887 new REST endpoint with correct spelling.
payara/Payara pull request #6836
Opened 2024-07-22 09:13 UTC by NotedSalmon

FISH 8887 typo in ClearCache
## Description

Added new REST endpoint with correct spelling. Could not change just the typo because Enterprise 6 calls this class from Community.
## Important Info
### Blockers

## Testing
### New tests

### Testing Performed

ran build
### Testing Environment

## Documentation

## Notes for Reviewers

2024-07-22 10:30 UTC, Pandrex247 commented on nucleus/payara-modules/hazelcast-bootstrap/src/main/java/fish/payara/nucleus/hazelcast/admin/ClearCache.java
> +
We can probably just drop it here in Community.
```suggestion
                description = "Clears a JCache or Hazalcast IMap")
```

2024-07-22 11:10 UTC, Pandrex247 requested changes
Doesn't appear to work:

`Cannot find cacheName in clear-cache command model, file a bug injection failed on fish.payara.nucleus.hazelcast.admin.ClearCache.cacheName with class java.lang.String`

2024-07-22 11:27 UTC, JamesHillyard commented
Jenkins test please

2024-07-24 14:03 UTC, Pandrex247 approved these changes

2024-07-24 14:13 UTC, merged