FISH-9502: adding validation to skip deploy on target if that is not …
payara/Payara pull request #6901
Opened 2024-08-20 01:26 UTC by breakponchito

…part of list

## Description

## Important Info
### Blockers

## Testing
### New tests

### Testing Performed

### Testing Environment

## Documentation

## Notes for Reviewers

2024-08-20 01:26 UTC, breakponchito commented
Jenkins test please

2024-08-21 13:38 UTC, Pandrex247 requested changes
Reintroduces FISH-6659

* Start Payara Server
* Create and start an instance
* Deploy clusterjsp to the instance
* Observe Modules and Components with entries
* Restart the server (DAS)
* The Modules and Components table will be empty.

2024-08-21 22:05 UTC, breakponchito commented
Jenkins test please

2024-08-21 22:17 UTC, breakponchito commented
Jenkins test please

2024-08-21 22:39 UTC, breakponchito commented
issue fixed for Modules and Components entries section

2024-08-21 23:15 UTC, breakponchito commented
Jenkins test please

2024-08-21 23:22 UTC, breakponchito commented
Jenkins test please

2024-08-22 00:37 UTC, breakponchito commented
Jenkins test please

2024-08-22 03:21 UTC, breakponchito commented
Jenkins test please

2024-08-22 13:05 UTC, Pandrex247 submitted a review, later dismissed
This seems to break redeployments for deployment groups.

- Start Payara Server
- Create a Deployment Group
- Create an Instance and add it to the deployment group
- Start the instance
- Deploy clusterjsp with the Deployment Group as its only target
- Application gets deployed and is accessible on the instance
- Restart the instance/deployment group
- Application doesn't get redeployed.

2024-08-22 13:53 UTC, breakponchito commented on nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/server/ApplicationLifecycle.java
> +        if (loadOnCurrentInstance(context) && isAppAvailable) {
already done

2024-08-27 00:08 UTC, breakponchito commented
Jenkins test please

2024-08-27 05:18 UTC, breakponchito commented
> This seems to break redeployments for deployment groups.
> 
> * Start Payara Server
> * Create a Deployment Group
> * Create an Instance and add it to the deployment group
> * Start the instance
> * Deploy clusterjsp with the Deployment Group as its only target
> * Application gets deployed and is accessible on the instance
> * Restart the instance/deployment group
> * Application doesn't get redeployed.

issue for deployment groups and clusters already fixed

2024-08-29 17:14 UTC, merged