Enhancement: Use <domain_dir>/lib/warlibs to enable fast devopment deployments
payara/Payara pull request #7097
Opened 2024-11-28 04:36 UTC by lprimak

## Description

Developer can copy all their dependencies to `<domain_dir>/lib/warlibs/` and use no-dependency skinny-war
for developer deployments, significantly improving deployment times.

## Testing
Tested skinny WAR deployment

2025-01-20 19:11 UTC, lprimak commented
@Pandrex247 this one is building a bit of a backlog now :)

2025-01-21 11:53 UTC, Pandrex247 commented
@lprimak 
I haven't forgotten you or your PRs 😝

We've recently been dealing with a number of high priority customer issues, internal targets, and attempting to catch up with and start contributing towards Jakarta EE 11 (particularly the Platform TCK and Jakarta Data).

Your two PRs don't look quick to review (particularly the CDI in EARs one!), so have unfortunately kept not making the cut for inclusion in our sprints. I do keep mentioning them during backlog grooming though, particularly since they've been open for quite a while now.

2025-01-21 18:45 UTC, lprimak commented
Thanks, the CDI-in-EAR one does the "heavy lift" to get things working for the other to, unfortunately I couldn't make it any smaller :)

2025-02-10 18:48 UTC, lprimak commented
I have now re-based this PR, so now it's the "top of the stack"
Thank you

2025-02-14 14:14 UTC, luiseufrasio requested changes
I experimented this error when I tried to deploy:
```
[#|2025-02-14T11:09:50.864-0300|SEVERE|Payara 6.2025.2|javax.enterprise.system.core|_ThreadID=299;_ThreadName=admin-thread-pool::admin-listener(6);_TimeMillis=1739542190864;_LevelValue=1000;_MessageID=NCLS-CORE-00026;|
  Exception during lifecycle processing
java.lang.Exception: java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "jakarta.faces.application.ViewHandler.getViewDeclarationLanguage(jakarta.faces.context.FacesContext, String)" because "viewHandler" is null

```

I also noticed that you created another branch: `flowlogix/warlib-up-to-date`

But the PR considers: `flowlogix/warlib`

2025-02-17 14:06 UTC, luiseufrasio approved these changes
I tested using the steps: https://gist.github.com/lprimak/167ff6d0e82f51f42abde57f17758026

It worked, the deploy occurred in 3 seconds.

2025-02-17 14:07 UTC, merged

2025-06-12 02:11 UTC, bdrx312 commented
Is there any documentation for this feature?

2025-06-12 02:35 UTC, bdrx312 commented
> Is there any documentation for this feature?

Never mind. Found https://github.com/payara/Payara-Documentation/pull/598/files